services:
  - type: web
    name: time-money
    runtime: node
    plan: 1c-2g
    buildCommand: "python3 -m pip install -r requirements-data.txt && npm install"
    startCommand: "node server.js"
    autoDeploy: true
    disk:
      name: time-money-data
      mountPath: /opt/render/project/src/data
      sizeGB: 20
