services:
  - type: web
    name: time-money-normal
    runtime: node
    plan: free
    buildCommand: python3 -m pip install --disable-pip-version-check -r requirements.txt && npm install && npm run build-data && npm test
    startCommand: npm start
    healthCheckPath: /
