services:
  - type: web
    name: time-money-normal
    runtime: node
    plan: free
    buildCommand: npm install && npm run build-data && npm test
    startCommand: npm start
    healthCheckPath: /
