const http=require('http');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const PORT=Number(process.env.PORT)||3000, TURN_MS=3*60*1000, DAY_BATTLE_MS=30*1000, MAX_PLAYERS=50, ROOM_TTL_MS=5*60*1000, DISCONNECT_GRACE_MS=5000, rooms=new Map(),sessions=new Map(),rate=new Map();
const ASSETS=JSON.parse(fs.readFileSync(path.join(__dirname,'session2_assets.json'),'utf8'));
const ASSET=new Map(ASSETS.map(a=>[a.id,a]));
function hash32(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function unitPrice(a,y,m){if(!a||y<a.year)return 0;let p=Number(a.base)||1;for(let yy=a.year;yy<=y;yy++){for(let mm=1;mm<=12;mm++){if(yy===a.year&&mm===1)continue;if(yy===y&&mm>m)break;let n=(hash32(`${a.id}|${yy}|${mm}`)/4294967296)-.5;let r=n*2*Number(a.vol||.02);if(yy===1997)r-=.035*(a.kind==='bonds'?.2:1);if(yy===1998)r+=.018;if(yy===2000&&/tech|over|fund/.test(a.kind))r-=.04;if(yy===2008&&a.kind!=='bonds'&&a.kind!=='gold')r-=.055;if(yy===2020&&a.kind==='coin')r+=.025;p=Math.max(a.kind==='coin'?.000001:.01,p*(1+r))}}return a.kind==='coin'?Number(p.toFixed(6)):Math.round(p)}
function market(room){if(!room.marketPrices)room.marketPrices={};for(const a of ASSETS)if(a.year<=room.year)room.marketPrices[a.id]=unitPrice(a,room.year,room.month);return room.marketPrices}
function positionValue(p,room){let n=0;for(const [id,q] of Object.entries(p.positions||{})){const a=ASSET.get(id),price=Number(room.marketPrices?.[id]||0);if(a&&price)n+=Number(q)*price*(Number(a.multiplier)||1)}return Math.round(n)}
function netWorth(p){return Math.round((Number(p.cash)||0)+(Number(p.assetValue)||0)-(Number(p.debt)||0)-(Number(p.loan)||0)-(Number(p.loanShark)||0))}
function authoritativeNetWorth(p,room){return Math.round((Number(p.cash)||0)+positionValue(p,room)-(Number(p.loan)||0)-(Number(p.loanShark)||0))}
function syncAssetValue(p,room){p.assetValue=positionValue(p,room);p.debt=(Number(p.loan)||0)+(Number(p.loanShark)||0);return p.assetValue}
function liquidateHoldings(p,room,need){let raised=0;const holdings=Object.entries(p.positions||{}).map(([id,q])=>{const a=ASSET.get(id),price=Number(room.marketPrices?.[id]||0),unit=price*(Number(a?.multiplier)||1);return {id,a,q:Number(q)||0,price,unit,value:Math.max(0,(Number(q)||0)*unit)}}).filter(x=>x.q>0&&x.unit>0).sort((a,b)=>b.value-a.value);for(const h of holdings){if(raised+1e-9>=need)break;const target=Math.min(h.value,need-raised);const qty=Math.min(h.q,Math.floor((target/h.unit)*1000000)/1000000);if(!(qty>0))continue;const proceeds=qty*h.unit;p.cash+=proceeds;raised+=proceeds;h.q-=qty;p.positions[h.id]=h.q;if(h.q<=1e-9){delete p.positions[h.id];delete p.avg[h.id]}}syncAssetValue(p,room);return raised}
function privateState(room,p){syncAssetValue(p,room);return {cash:p.cash,positions:p.positions||{},avg:p.avg||{},loan:p.loan||0,loanShark:p.loanShark||0,netWorth:authoritativeNetWorth(p,room),assetValue:p.assetValue,debt:p.debt}}
const DAY_ASSETS=ASSETS.filter(a=>a&&a.kind!=='real'&&a.kind!=='bonds'&&a.kind!=='gold'&&Number(a.base)>0);
function dayAsset(room){const listed=DAY_ASSETS.filter(a=>Number(a.year||1990)<=Number(room.year||1990));return listed[crypto.randomInt(0,Math.max(1,listed.length))]||DAY_ASSETS[0];}
function dayPct(p,price){const q=Number(p.dayQty)||0,cost=Number(p.dayCost)||0;return q>0&&cost>0?((price-(cost/q))/(cost/q))*100:0}
function dayView(room,p){const d=room.dayBattle||{};const price=Number(d.price)||0;return {active:!!d.active,assetId:d.assetId||null,assetName:d.assetName||null,currentPrice:price,endAt:Number(d.deadline)||0,serverNow:Date.now(),history:Array.isArray(d.history)?d.history.slice(-120):[],myQty:Number(p?.dayQty)||0,myCost:Number(p?.dayCost)||0,myPct:p?dayPct(p,price):0,myUnrealized:p?Math.round((price*(Number(p.dayQty)||0))-(Number(p.dayCost)||0)):0,winner:d.winner||null,loser:d.loser||null,winnerPct:d.winnerPct??null,loserPct:d.loserPct??null,settled:!!d.settled};}
function tickDayBattle(room){if(!room.dayBattle?.active)return;const d=room.dayBattle;const p=Math.max(.01,Number(d.price)||1);const next=Math.max(.01,p*(1+(crypto.randomInt(-60,61)/10000)));d.price=Math.round(next*100)/100;d.history=Array.isArray(d.history)?d.history:[];d.history.push(d.price);if(d.history.length>120)d.history=d.history.slice(-120);for(const pl of room.players.values())pl.dayPct=dayPct(pl,d.price);}
function json(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer'});res.end(body)}
function ip(req){return (req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim()}
function limited(req){const k=ip(req),now=Date.now(),x=rate.get(k)||{t:now,n:0};if(now-x.t>60000){x.t=now;x.n=0}x.n++;rate.set(k,x);return x.n>240}
function token(){return crypto.randomBytes(32).toString('hex')}
function roomCode(){let c;do c=String(crypto.randomInt(0,1000000)).padStart(6,'0');while(rooms.has(c));return c}
function safeName(n){return String(n||'Player').trim().slice(0,20)||'Player'}
function netWorth(p){return Math.round((Number(p.cash)||0)+(Number(p.assetValue)||0)-(Number(p.debt)||0))}
function debtExcludedWealth(p,room){return Math.round((Number(p.cash)||0)+positionValue(p,room))}
function markAutoReadyIfBroke(room){if(!room.started||room.finished||room.dayBattle?.active)return false;let changed=false;for(const p of room.players.values()){if(!p.ready&&debtExcludedWealth(p,room)<=0){p.ready=true;p.autoReady=true;p.autoReadyReason='무부채 재산 0원 이하';changed=true}}return changed}
function markDisconnectedReady(room,now=Date.now()){if(!room.started||room.finished||room.dayBattle?.active)return false;let changed=false;for(const p of room.players.values()){if(!p.ready&&!p.left&&p.lastSeen&&now-p.lastSeen>=DISCONNECT_GRACE_MS){p.ready=true;p.autoReady=true;p.autoReadyReason='접속 끊김 자동 승인';p.disconnected=true;changed=true}}return changed}
function maybeAdvance(room){if(!room.started||room.finished||room.dayBattle?.active)return {advanced:false,finished:false};markAutoReadyIfBroke(room);markDisconnectedReady(room);if([...room.players.values()].every(x=>x.ready))return advance(room);return {advanced:false,finished:false,readyCount:[...room.players.values()].filter(x=>x.ready).length}}
function periodFor(y,m){const startMonth=((m-1)%6)+1;const startM=m-startMonth+1;const sy=y;const ey=y,em=Math.min(startM+5,12);return {start:{year:sy,month:startM},end:{year:ey,month:em}}}
function activateCountdown(room){if(room.startAt && !room.started && Date.now()>=room.startAt){room.startAt=0;startRoom(room);return true}return false}
function view(room,playerId){activateCountdown(room);for(const x of room.players.values())syncAssetValue(x,room);markAutoReadyIfBroke(room);markDisconnectedReady(room);if(room.dayBattle?.active&&Date.now()>=room.dayBattle.deadline)finishDayBattle(room);const p=playerId?room.players.get(playerId):null;const dayBattleLeaderboard=[...room.players.values()].map(x=>({name:x.name,pct:Number.isFinite(x.dayPct)?x.dayPct:null})).sort((a,b)=>(b.pct??-Infinity)-(a.pct??-Infinity));return {roomCode:room.code,hostId:room.hostId,started:room.started,finished:room.finished,startAt:room.startAt||0,countdownActive:!!(room.startAt&&!room.started),year:room.year,month:room.month,turn:room.turn||0,deadline:room.deadline,turnDeadline:room.turnDeadline||room.deadline,periodStart:room.periodStart,periodEnd:room.periodEnd,playerCount:room.players.size,readyCount:[...room.players.values()].filter(x=>x.ready).length,meReady:!!p?.ready,canStart:room.players.size>=2&&room.hostId===playerId&&!room.started&&!room.finished,players:[...room.players.values()].filter(x=>!x.left).map(x=>({id:x.id,name:x.name,ready:!!x.ready,autoReady:!!x.autoReady,autoReadyReason:x.autoReadyReason||'',netWorth:authoritativeNetWorth(x,room)})),dayBattle:room.dayBattle||{active:false},dayBattleLeaderboard,leaderboard:[...room.players.values()].filter(x=>!x.left).map(x=>({name:x.name,netWorth:authoritativeNetWorth(x,room)})).sort((a,b)=>b.netWorth-a.netWorth),market:{prices:market(room)},turnPlayerId:room.turnPlayerId||null,me:p?privateState(room,p):null,dayTrade:dayView(room,p)}}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>200000)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function auth(room,t){const s=sessions.get(t);if(!s||s.room!==room.code||s.exp<Date.now()){if(s&&s.exp<Date.now())sessions.delete(t);return null}const p=room.players.get(s.id)||null;if(p){p.lastSeen=Date.now();p.disconnected=false;if(!p.left)room.emptySince=0}return p}
function maybeDayBattle(room){room.dayBattle={active:false,startedAt:0,deadline:0,pausedMs:0};if(room.players.size<2)return;if(room.year===1990&&room.month===1)return;if(crypto.randomInt(0,100)<15){const remaining=Math.max(0,(room.turnDeadline||room.deadline)-Date.now());room.turnRemainingMs=remaining;room.deadline=0;const a=dayAsset(room);room.dayBattle={active:true,startedAt:Date.now(),deadline:Date.now()+DAY_BATTLE_MS,pausedMs:remaining,assetId:a.id,assetName:a.name,price:Number(a.base)||1,history:[Number(a.base)||1],winner:null,loser:null,settled:false};for(const p of room.players.values()){p.dayBudget=100;p.dayCash=100;p.dayQty=0;p.dayCost=0;p.dayPct=0;p.dayTradePnl=0;p.dayReady=false;}}}
function startRoom(room){if(room.started||room.finished||room.players.size<2)return false;room.startAt=0;room.started=true;room.year=1990;room.month=1;room.periodStart={year:1990,month:1};room.periodEnd={year:1990,month:6};room.turnPlayerId=null;market(room);room.deadline=Date.now()+TURN_MS;room.turnDeadline=room.deadline;room.turnRemainingMs=TURN_MS;room.dayBattle={active:false,startedAt:0,deadline:0,pausedMs:0};for(const p of room.players.values()){p.ready=false;p.autoReady=false;p.autoReadyReason='';p.disconnected=false;p.left=false;p.lastSeen=Date.now()}return true}
function advance(room){if(room.finished)return {advanced:false,finished:true};if(room.year===2026&&room.month===7){room.finished=true;room.finishedAt=Date.now();room.deadline=0;for(const p of room.players.values())p.ready=false;return {advanced:false,finished:true}}room.month+=6;while(room.month>12){room.month-=12;room.year++}if(room.year>2026){room.finished=true;room.deadline=0;for(const p of room.players.values())p.ready=false;return {advanced:false,finished:true}}room.turn=(Number(room.turn)||0)+1;room.periodStart={year:room.year,month:room.month};room.periodEnd={year:room.year,month:Math.min(12,room.month+5)};for(const p of room.players.values()){p.ready=false;p.autoReady=false;p.autoReadyReason='';if(p.loan)p.loan=Math.round(p.loan*Math.pow(1.01,6));if(p.loanShark)p.loanShark=Math.round(p.loanShark*Math.pow(1.05,6));syncAssetValue(p,room);if(room.month===1){if(p.loan)p.cash=Math.max(0,p.cash-Math.round(p.loan*.12));if(p.loanShark)p.cash=Math.max(0,p.cash-Math.round(p.loanShark*.60))}}market(room);room.deadline=Date.now()+TURN_MS;room.turnDeadline=room.deadline;room.turnRemainingMs=TURN_MS;maybeDayBattle(room);return {advanced:true,finished:false}}
function finishDayBattle(room){if(!room.dayBattle?.active)return;if(Date.now()<room.dayBattle.deadline)return;const active=[...room.players.values()];const price=Number(room.dayBattle.price)||0;for(const p of active){const q=Number(p.dayQty)||0;const dayValue=Math.round(q*price);const pnl=dayValue-(Number(p.dayCost)||0);p.dayTradePnl=pnl;if(q>0)p.dayCash+=dayValue;p.dayQty=0;p.dayCost=0;p.cash+=Math.max(0,Number(p.dayCash)||0);p.dayCash=0}const ranked=active.map(x=>({p:x,pct:Number.isFinite(x.dayPct)?x.dayPct:-Infinity})).sort((a,b)=>b.pct-a.pct);const first=ranked[0]?.p,last=ranked[ranked.length-1]?.p;if(first)syncAssetValue(first,room);if(last)syncAssetValue(last,room);const beforeFirst=first?Math.max(0,authoritativeNetWorth(first,room)):0;const beforeLast=last?Math.max(0,authoritativeNetWorth(last,room)):0;if(first)first.cash+=Math.round(beforeFirst*.5);if(last&&last.id!==first?.id)last.cash=Math.max(0,last.cash-Math.round(beforeLast*.5));const paused=Math.max(0,Number(room.dayBattle.pausedMs)||0);room.dayBattle={...room.dayBattle,active:false,winner:first?.name||null,loser:last?.name||null,pausedMs:paused,settled:true,winnerPct:first?.dayPct??null,loserPct:last?.dayPct??null,settledAt:Date.now()};room.deadline=Date.now()+paused;room.turnDeadline=room.deadline;room.turnRemainingMs=paused;active.forEach(x=>{x.dayPct=undefined;x.dayReady=false;x.dayBudget=100;x.dayCash=100;x.dayQty=0;x.dayCost=0})}
function create(name){const code=roomCode();const id=crypto.randomUUID(),t=token();const room={code,hostId:id,year:1990,month:1,deadline:0,periodStart:{year:1990,month:1},periodEnd:{year:1990,month:6},started:false,finished:false,createdAt:Date.now(),finishedAt:0,players:new Map(),dayBattle:{active:false,startedAt:0,deadline:0}};rooms.set(code,room);room.players.set(id,{id,name:safeName(name),cash:100000000,assetValue:0,debt:0,positions:{},avg:{},loan:0,loanShark:0,ready:false,dayReady:false,lastSeen:Date.now()});sessions.set(t,{room:code,id,exp:Date.now()+86400000});return {token:t,id,code}}
async function handler(req,res){if(limited(req))return json(res,429,{error:'rate limit'});const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(__dirname,'index.html')).pipe(res)}
try{
if(req.method==='POST'&&u.pathname==='/api/rooms'){const b=await body(req);const r=create(b.name);return json(res,200,{roomCode:r.code,sessionToken:r.token,playerId:r.id,started:false,year:1990,month:1,deadline:0,periodStart:{year:1990,month:1},periodEnd:{year:1990,month:6}})}
if(req.method==='POST'&&u.pathname==='/api/rooms/join'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});if(room.finished)return json(res,409,{error:'이미 종료된 방입니다.'});if(room.started)return json(res,409,{error:'이미 시작된 방입니다.'});if(room.players.size>=MAX_PLAYERS)return json(res,409,{error:'방이 가득 찼습니다.'});const id=crypto.randomUUID(),t=token();room.players.set(id,{id,name:safeName(b.name),cash:100000000,assetValue:0,debt:0,positions:{},avg:{},loan:0,loanShark:0,ready:false,dayReady:false,lastSeen:Date.now()});sessions.set(t,{room:room.code,id,exp:Date.now()+86400000});return json(res,200,{...view(room,id),sessionToken:t,playerId:id})}
if(req.method==='POST'&&u.pathname==='/api/rooms/start'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(room.hostId!==p.id)return json(res,403,{error:'방장만 대전을 시작할 수 있습니다.'});if(room.players.size<2)return json(res,409,{error:'최소 2명이 필요합니다.'});if(room.started)return json(res,409,{error:'이미 시작된 대전입니다.'});room.startAt=Date.now()+10000;return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/progress'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});const pl=room.players.get(p.id);if(!pl)return json(res,401,{error:'플레이어를 찾을 수 없습니다.'});if(!room.started)return json(res,409,{error:'아직 대전이 시작되지 않았습니다.'});if(room.finished)return json(res,200,{...view(room,p.id),finished:true});markAutoReadyIfBroke(room);if(pl.ready)return json(res,200,{...view(room,p.id),alreadyReady:true});pl.ready=true;pl.autoReady=false;pl.autoReadyReason='';let result={advanced:false,finished:false};if(!room.dayBattle?.active)result=maybeAdvance(room);return json(res,200,{...view(room,p.id),...result})}
if(req.method==='POST'&&u.pathname==='/api/rooms/trade'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'진행 중인 대전이 아닙니다.'});const a=ASSET.get(String(b.assetId||'')),side=b.side,qty=Math.floor(Number(b.qty)*1000000)/1000000;if(!a||!['buy','sell'].includes(side)||!Number.isFinite(qty)||qty<=0)return json(res,400,{error:'잘못된 거래입니다.'});if(a.year>room.year)return json(res,409,{error:'아직 거래할 수 없는 자산입니다.'});const price=Number(room.marketPrices?.[a.id]||0),unit=price*(Number(a.multiplier)||1),value=qty*unit;if(!price||!Number.isFinite(value))return json(res,409,{error:'시장 가격을 확인할 수 없습니다.'});const owned=Number(p.positions?.[a.id]||0);if(side==='buy'){if(Number(p.cash)<value)return json(res,409,{error:'현금이 부족합니다.',shortage:true,required:value,available:Number(p.cash)||0});const old=owned,oldAvg=Number(p.avg?.[a.id]||0);p.cash-=value;p.positions[a.id]=old+qty;p.avg[a.id]=old?((oldAvg*old)+value)/(old+qty):value}else{if(owned<qty)return json(res,409,{error:'보유 수량이 부족합니다.'});p.cash+=value;p.positions[a.id]=owned-qty;if(!p.positions[a.id]){delete p.positions[a.id];delete p.avg[a.id]}}syncAssetValue(p,room);return json(res,200,{...view(room,p.id),trade:{assetId:a.id,side,qty,value,price}})}
if(req.method==='POST'&&u.pathname==='/api/rooms/loan'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'진행 중인 대전이 아닙니다.'});const kind=b.kind==='shark'?'shark':'bank',amount=Number(b.amount);if(!Number.isInteger(amount)||amount<1)return json(res,400,{error:'대출 금액이 잘못되었습니다.'});syncAssetValue(p,room);const nw=Math.abs(authoritativeNetWorth(p,room)),max=kind==='bank'?Math.floor(nw*1.5):Math.floor(nw*4),used=kind==='bank'?Number(p.loan)||0:Number(p.loanShark)||0,v=Math.min(amount,Math.max(0,max-used));if(v<1)return json(res,409,{error:'대출 한도가 없습니다.'});if(kind==='bank')p.loan=(Number(p.loan)||0)+v;else p.loanShark=(Number(p.loanShark)||0)+v;p.cash+=v;syncAssetValue(p,room);return json(res,200,{...view(room,p.id),loaned:v,kind})}
if(req.method==='POST'&&u.pathname==='/api/rooms/liquidate'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});const need=Math.max(0,Math.ceil(Number(b.amount)||0));if(!room.started||room.finished||need<1)return json(res,409,{error:'매도할 수 없습니다.'});let raised=0;const holdings=Object.entries(p.positions||{}).map(([id,q])=>{const a=ASSET.get(id),price=Number(room.marketPrices?.[id]||0),unit=price*(Number(a?.multiplier)||1);return {id,a,q:Number(q)||0,price,unit,value:Math.max(0,Math.round((Number(q)||0)*unit))}}).filter(x=>x.q>0&&x.price>0).sort((a,b)=>b.value-a.value);for(const h of holdings){if(raised>=need)break;const target=Math.min(h.value,need-raised);const qty=Math.min(h.q,Math.floor((target/h.unit)*1000000)/1000000);const proceeds=Math.min(h.value,qty*h.unit);p.cash+=proceeds;raised+=proceeds;p.positions[h.id]=h.q-qty;if(p.positions[h.id]<=0){delete p.positions[h.id];delete p.avg[h.id]}}syncAssetValue(p,room);if(raised<need)return json(res,409,{error:'보유 투자물을 모두 매도해도 부족 금액을 마련할 수 없습니다.',raised,required:need,shortage:true});return json(res,200,{...view(room,p.id),liquidated:raised,required:need})}
if(req.method==='POST'&&u.pathname==='/api/rooms/score'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});const pl=room.players.get(p.id);if(!pl)return json(res,401,{error:'플레이어를 찾을 수 없습니다.'});if(!Number.isFinite(Number(b.assetValue))||!Number.isFinite(Number(b.cash))||!Number.isFinite(Number(b.debt)))return json(res,400,{error:'잘못된 자산 데이터'});pl.cash=Math.max(0,Math.round(Number(b.cash)));pl.assetValue=Math.max(0,Math.round(Number(b.assetValue)));pl.debt=Math.max(0,Math.round(Number(b.debt)));return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/daytrade'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished||!room.dayBattle?.active)return json(res,409,{error:'진행 중인 전체참여 단타가 없습니다.'});const pl=room.players.get(p.id);const side=b.side==='sell'?'sell':'buy',qty=Math.max(0.0001,Number(b.qty)||0),price=Number(room.dayBattle.price)||0;if(!(qty>0)||!Number.isFinite(qty))return json(res,400,{error:'거래 수량이 잘못되었습니다.'});if(side==='buy'){const cost=price*qty;if(!Number.isFinite(cost)||cost<=0)return json(res,409,{error:'단타 거래 금액이 잘못되었습니다.'});if((Number(pl.dayCash)||0)+1e-9<cost)return json(res,409,{error:'전체참여 단타용 자금이 부족합니다.',available:Number(pl.dayCash)||0,required:cost});const oldQ=Number(pl.dayQty)||0,oldCost=Number(pl.dayCost)||0;pl.dayCash-=cost;pl.dayQty=oldQ+qty;pl.dayCost=oldCost+cost}else{if((Number(pl.dayQty)||0)+1e-9<qty)return json(res,409,{error:'단타 보유수량이 부족합니다.'});const avg=(Number(pl.dayCost)||0)/(Number(pl.dayQty)||1);pl.dayCash+=price*qty;pl.dayQty-=qty;pl.dayCost=Math.max(0,avg*pl.dayQty)}pl.dayPct=dayPct(pl,price);return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/daybattle/score'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.dayBattle?.active)return json(res,409,{error:'진행 중인 전체참여 단타가 없습니다.'});const pl=room.players.get(p.id);pl.dayPct=dayPct(pl,Number(room.dayBattle.price)||0);return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/force-progress'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(room.hostId!==p.id)return json(res,403,{error:'방장만 턴을 강제로 넘길 수 있습니다.'});if(!room.started||room.finished)return json(res,409,{error:'강제 진행할 수 없는 상태입니다.'});if(room.dayBattle?.active)return json(res,409,{error:'전체참여 단타가 끝난 뒤 강제 진행할 수 있습니다.'});for(const x of room.players.values()){x.ready=false;x.autoReady=false;x.autoReadyReason='';}const result=advance(room);return json(res,200,{...view(room,p.id),...result,forcedByHost:true})}
if(req.method==='POST'&&u.pathname==='/api/rooms/leave'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(room.started&&!room.finished){p.ready=true;p.autoReady=true;p.autoReadyReason='플레이어 퇴장 자동 승인';p.left=true;p.disconnected=true;p.lastSeen=Date.now();sessions.delete(b.sessionToken);if(room.hostId===p.id){const next=[...room.players.values()].find(x=>x.id!==p.id&&!x.left);room.hostId=next?.id||null}const result=maybeAdvance(room);return json(res,200,{ok:true,autoReady:true,...result})}room.players.delete(p.id);sessions.delete(b.sessionToken);if(room.hostId===p.id){const next=room.players.values().next().value;room.hostId=next?.id||null;room.startAt=0}if(room.players.size===0)room.emptySince=Date.now();return json(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname.startsWith('/api/rooms/')){const code=u.pathname.split('/').pop(),room=rooms.get(code),t=u.searchParams.get('sessionToken');if(!room||!auth(room,t))return json(res,401,{error:'인증 실패'});const p=auth(room,t);if(room.started&&!room.finished&&!room.dayBattle?.active&&Date.now()>=room.deadline){advance(room)}return json(res,200,view(room,p.id))}
return json(res,404,{error:'not found'})
}catch(e){return json(res,400,{error:'bad request'})}}
function allPlayersGone(room,now){
  if(room.players.size===0)return true;
  for(const p of room.players.values()){
    if(p.left)continue;
    if(!p.lastSeen||now-p.lastSeen<DISCONNECT_GRACE_MS)return false;
  }
  return true;
}
setInterval(()=>{
  const now=Date.now();
  for(const [t,s] of sessions) if(s.exp<now) sessions.delete(t);
  for(const [c,r] of rooms){
    if(allPlayersGone(r,now)){
      if(!r.emptySince)r.emptySince=now;
      if(now-r.emptySince>=ROOM_TTL_MS){
        for(const [t,s] of sessions) if(s.room===r.code) sessions.delete(t);
        rooms.delete(c);
        continue;
      }
    }else r.emptySince=0
    if(r.dayBattle?.active){tickDayBattle(r);finishDayBattle(r);}
    if(r.started&&!r.finished&&!r.dayBattle?.active){markAutoReadyIfBroke(r,now);markDisconnectedReady(r,now);if([...r.players.values()].every(x=>x.ready)) advance(r);else if(now>=r.deadline) advance(r)}
  }
},1000);
http.createServer(handler).listen(PORT,()=>console.log(`TIME&MONEY v6 server on ${PORT}`));
