const http=require('http');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const PORT=Number(process.env.PORT)||3000, TURN_MS=3*60*1000, DAY_BATTLE_MS=30*1000, MAX_PLAYERS=50, ROOM_TTL_MS=60*60*1000, rooms=new Map(),sessions=new Map(),rate=new Map();
const ASSETS=JSON.parse(fs.readFileSync(path.join(__dirname,'session2_assets.json'),'utf8'));
const DAY_ASSETS=ASSETS.filter(a=>a&&a.kind!=='real'&&a.kind!=='bonds'&&a.kind!=='gold'&&Number(a.base)>0);
function dayAsset(room){const listed=DAY_ASSETS.filter(a=>Number(a.year||1990)<=Number(room.year||1990));return listed[crypto.randomInt(0,Math.max(1,listed.length))]||DAY_ASSETS[0];}
function dayPct(p,price){const q=Number(p.dayQty)||0,cost=Number(p.dayCost)||0;return q>0&&cost>0?((price-(cost/q))/(cost/q))*100:0}
function dayView(room,p){const d=room.dayBattle||{};const price=Number(d.price)||0;return {active:!!d.active,assetId:d.assetId||null,assetName:d.assetName||null,currentPrice:price,endAt:Number(d.deadline)||0,serverNow:Date.now(),history:Array.isArray(d.history)?d.history.slice(-120):[],myQty:Number(p?.dayQty)||0,myCost:Number(p?.dayCost)||0,myPct:p?dayPct(p,price):0,myUnrealized:p?Math.round((price*(Number(p.dayQty)||0))-(Number(p.dayCost)||0)):0,winner:d.winner||null,loser:d.loser||null,settled:!!d.settled};}
function tickDayBattle(room){if(!room.dayBattle?.active)return;const d=room.dayBattle;const p=Math.max(.01,Number(d.price)||1);const next=Math.max(.01,p*(1+(crypto.randomInt(-60,61)/10000)));d.price=Math.round(next*100)/100;d.history=Array.isArray(d.history)?d.history:[];d.history.push(d.price);if(d.history.length>120)d.history=d.history.slice(-120);for(const pl of room.players.values())pl.dayPct=dayPct(pl,d.price);}
function json(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer'});res.end(body)}
function ip(req){return (req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim()}
function limited(req){const k=ip(req),now=Date.now(),x=rate.get(k)||{t:now,n:0};if(now-x.t>60000){x.t=now;x.n=0}x.n++;rate.set(k,x);return x.n>240}
function token(){return crypto.randomBytes(32).toString('hex')}
function roomCode(){let c;do c=String(crypto.randomInt(0,1000000)).padStart(6,'0');while(rooms.has(c));return c}
function safeName(n){return String(n||'Player').trim().slice(0,20)||'Player'}
function netWorth(p){return Math.round((Number(p.cash)||0)+(Number(p.assetValue)||0)-(Number(p.debt)||0))}
function periodFor(y,m){const startMonth=((m-1)%6)+1;const startM=m-startMonth+1;const sy=y;const ey=y,em=Math.min(startM+5,12);return {start:{year:sy,month:startM},end:{year:ey,month:em}}}
function activateCountdown(room){if(room.startAt && !room.started && Date.now()>=room.startAt){room.startAt=0;startRoom(room);return true}return false}
function view(room,playerId){activateCountdown(room);if(room.dayBattle?.active&&Date.now()>=room.dayBattle.deadline)finishDayBattle(room);const p=playerId?room.players.get(playerId):null;const dayBattleLeaderboard=[...room.players.values()].map(x=>({name:x.name,pct:Number.isFinite(x.dayPct)?x.dayPct:null})).sort((a,b)=>(b.pct??-Infinity)-(a.pct??-Infinity));return {roomCode:room.code,hostId:room.hostId,started:room.started,finished:room.finished,startAt:room.startAt||0,countdownActive:!!(room.startAt&&!room.started),year:room.year,month:room.month,deadline:room.deadline,turnDeadline:room.turnDeadline||room.deadline,periodStart:room.periodStart,periodEnd:room.periodEnd,playerCount:room.players.size,readyCount:[...room.players.values()].filter(x=>x.ready).length,meReady:!!p?.ready,canStart:room.players.size>=2&&room.hostId===playerId&&!room.started&&!room.finished,dayBattle:room.dayBattle||{active:false},dayBattleLeaderboard,leaderboard:[...room.players.values()].map(x=>({name:x.name,netWorth:netWorth(x)})).sort((a,b)=>b.netWorth-a.netWorth),dayTrade:dayView(room,p),dayBattleLeaderboard}}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>200000)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function auth(room,t){const p=sessions.get(t);if(!p||p.room!==room.code||p.exp<Date.now()){if(p&&p.exp<Date.now())sessions.delete(t);return null}return p}
function maybeDayBattle(room){room.dayBattle={active:false,startedAt:0,deadline:0,pausedMs:0};if(room.players.size<2)return;if(room.year===1990&&room.month===1)return;if(crypto.randomInt(0,10)<10){const remaining=Math.max(0,(room.turnDeadline||room.deadline)-Date.now());room.turnRemainingMs=remaining;room.deadline=0;const a=dayAsset(room);room.dayBattle={active:true,startedAt:Date.now(),deadline:Date.now()+DAY_BATTLE_MS,pausedMs:remaining,assetId:a.id,assetName:a.name,price:Number(a.base)||1,history:[Number(a.base)||1],winner:null,loser:null,settled:false};for(const p of room.players.values()){p.dayReady=false;p.dayQty=0;p.dayCost=0;p.dayPct=0;p.dayTradePnl=0}}}
function startRoom(room){if(room.started||room.finished||room.players.size<2)return false;room.startAt=0;room.started=true;room.year=1990;room.month=1;room.periodStart={year:1990,month:1};room.periodEnd={year:1990,month:6};room.deadline=Date.now()+TURN_MS;room.turnDeadline=room.deadline;room.turnRemainingMs=TURN_MS;room.dayBattle={active:false,startedAt:0,deadline:0,pausedMs:0};for(const p of room.players.values())p.ready=false;return true}
function advance(room){if(room.finished)return {advanced:false};if(room.year===2026&&room.month===6){room.finished=true;room.finishedAt=Date.now();room.deadline=0;for(const p of room.players.values())p.ready=false;return {advanced:false,finished:true}}
room.month++;if(room.month>12){room.month=1;room.year++}const period=periodFor(room.year,room.month);room.periodStart=period.start;room.periodEnd=period.end;room.deadline=Date.now()+TURN_MS;room.turnDeadline=room.deadline;room.turnRemainingMs=TURN_MS;for(const p of room.players.values())p.ready=false;maybeDayBattle(room);return {advanced:true,finished:false}}
function finishDayBattle(room){if(!room.dayBattle?.active)return;if(Date.now()<room.dayBattle.deadline)return;const active=[...room.players.values()];const price=Number(room.dayBattle.price)||0;for(const p of active){const q=Number(p.dayQty)||0;if(q>0){p.cash+=Math.round(q*price);p.dayTradePnl=Math.round(q*price-(Number(p.dayCost)||0));p.dayQty=0;p.dayCost=0}}const ranked=active.map(x=>({p:x,pct:Number.isFinite(x.dayPct)?x.dayPct:-Infinity})).sort((a,b)=>b.pct-a.pct);const first=ranked[0]?.p,last=ranked[ranked.length-1]?.p;const beforeFirst=first?Math.max(0,netWorth(first)):0;const beforeLast=last?Math.max(0,netWorth(last)):0;if(first)first.cash+=Math.round(beforeFirst*.5);if(last&&last.id!==first?.id)last.cash=Math.max(0,last.cash-Math.round(beforeLast*.5));const paused=Math.max(0,Number(room.dayBattle.pausedMs)||0);room.dayBattle={...room.dayBattle,active:false,winner:first?.name||null,loser:last?.name||null,pausedMs:paused,settled:true,winnerPct:first?.dayPct??null,loserPct:last?.dayPct??null,settledAt:Date.now()};room.deadline=Date.now()+paused;room.turnDeadline=room.deadline;room.turnRemainingMs=paused;active.forEach(x=>{x.dayPct=undefined;x.dayReady=false})}
function create(name){const code=roomCode();const id=crypto.randomUUID(),t=token();const room={code,hostId:id,year:1990,month:1,deadline:0,periodStart:{year:1990,month:1},periodEnd:{year:1990,month:6},started:false,finished:false,createdAt:Date.now(),finishedAt:0,players:new Map(),dayBattle:{active:false,startedAt:0,deadline:0}};rooms.set(code,room);room.players.set(id,{id,name:safeName(name),cash:100000000,assetValue:0,debt:0,ready:false,dayReady:false});sessions.set(t,{room:code,id,exp:Date.now()+86400000});return {token:t,id,code}}
async function handler(req,res){if(limited(req))return json(res,429,{error:'rate limit'});const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(__dirname,'index.html')).pipe(res)}
try{
if(req.method==='POST'&&u.pathname==='/api/rooms'){const b=await body(req);const r=create(b.name);return json(res,200,{roomCode:r.code,sessionToken:r.token,playerId:r.id,started:false,year:1990,month:1,deadline:0,periodStart:{year:1990,month:1},periodEnd:{year:1990,month:6}})}
if(req.method==='POST'&&u.pathname==='/api/rooms/join'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});if(room.finished)return json(res,409,{error:'이미 종료된 방입니다.'});if(room.started)return json(res,409,{error:'이미 시작된 방입니다.'});if(room.players.size>=MAX_PLAYERS)return json(res,409,{error:'방이 가득 찼습니다.'});const id=crypto.randomUUID(),t=token();room.players.set(id,{id,name:safeName(b.name),cash:100000000,assetValue:0,debt:0,ready:false,dayReady:false});sessions.set(t,{room:room.code,id,exp:Date.now()+86400000});return json(res,200,{...view(room,id),sessionToken:t,playerId:id})}
if(req.method==='POST'&&u.pathname==='/api/rooms/start'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(room.hostId!==p.id)return json(res,403,{error:'방장만 대전을 시작할 수 있습니다.'});if(room.players.size<2)return json(res,409,{error:'최소 2명이 필요합니다.'});if(room.started)return json(res,409,{error:'이미 시작된 대전입니다.'});room.startAt=Date.now()+10000;return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/progress'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});const pl=room.players.get(p.id);if(!pl)return json(res,401,{error:'플레이어를 찾을 수 없습니다.'});if(!room.started)return json(res,409,{error:'아직 대전이 시작되지 않았습니다.'});if(room.finished)return json(res,200,{...view(room,p.id),finished:true});if(pl.ready)return json(res,200,{...view(room,p.id),alreadyReady:true});pl.ready=true;let result={advanced:false,finished:false};if(!room.dayBattle?.active&&( [...room.players.values()].every(x=>x.ready)||Date.now()>=room.deadline))result=advance(room);return json(res,200,{...view(room,p.id),...result})}
if(req.method==='POST'&&u.pathname==='/api/rooms/score'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});const pl=room.players.get(p.id);if(!pl)return json(res,401,{error:'플레이어를 찾을 수 없습니다.'});if(!Number.isFinite(Number(b.assetValue))||!Number.isFinite(Number(b.cash))||!Number.isFinite(Number(b.debt)))return json(res,400,{error:'잘못된 자산 데이터'});pl.cash=Math.max(0,Math.round(Number(b.cash)));pl.assetValue=Math.max(0,Math.round(Number(b.assetValue)));pl.debt=Math.max(0,Math.round(Number(b.debt)));return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/daytrade'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished||!room.dayBattle?.active)return json(res,409,{error:'진행 중인 전체참여 단타가 없습니다.'});const pl=room.players.get(p.id);const side=b.side==='sell'?'sell':'buy',qty=Math.max(1,Math.floor(Number(b.qty)||0)),price=Number(room.dayBattle.price)||0;if(side==='buy'){const cost=Math.round(price*qty);if(pl.cash<cost)return json(res,409,{error:'단타 매수 자금이 부족합니다.'});const oldQ=Number(pl.dayQty)||0,oldCost=Number(pl.dayCost)||0;pl.cash-=cost;pl.dayQty=oldQ+qty;pl.dayCost=oldCost+cost}else{if((Number(pl.dayQty)||0)<qty)return json(res,409,{error:'단타 보유수량이 부족합니다.'});const avg=(Number(pl.dayCost)||0)/(Number(pl.dayQty)||1);pl.cash+=Math.round(price*qty);pl.dayQty-=qty;pl.dayCost=Math.max(0,Math.round(avg*pl.dayQty))}pl.dayPct=dayPct(pl,price);return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/daybattle/score'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.dayBattle?.active)return json(res,409,{error:'진행 중인 전체참여 단타가 없습니다.'});const pl=room.players.get(p.id);pl.dayPct=dayPct(pl,Number(room.dayBattle.price)||0);return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/leave'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});room.players.delete(p.id);sessions.delete(b.sessionToken);if(room.hostId===p.id){const next=room.players.values().next().value;room.hostId=next?.id||null;room.startAt=0}if(room.players.size===0)rooms.delete(room.code);else if(room.started&&room.players.size===1){/* keep the room alive for reconnect; no silent auto-win */}return json(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname.startsWith('/api/rooms/')){const code=u.pathname.split('/').pop(),room=rooms.get(code),t=u.searchParams.get('sessionToken');if(!room||!auth(room,t))return json(res,401,{error:'인증 실패'});const p=auth(room,t);if(room.started&&!room.finished&&!room.dayBattle?.active&&Date.now()>=room.deadline){advance(room)}return json(res,200,view(room,p.id))}
return json(res,404,{error:'not found'})
}catch(e){return json(res,400,{error:'bad request'})}}
setInterval(()=>{
  const now=Date.now();
  for(const [t,s] of sessions) if(s.exp<now) sessions.delete(t);
  for(const [c,r] of rooms){
    if(r.players.size===0){rooms.delete(c);continue}
    if(r.finished&&r.finishedAt&&now-r.finishedAt>ROOM_TTL_MS){rooms.delete(c);continue}
    if(r.dayBattle?.active) finishDayBattle(r);
    if(r.started&&!r.finished&&!r.dayBattle?.active&&Date.now()>=r.deadline) advance(r);
  }
},1000);
http.createServer(handler).listen(PORT,()=>console.log(`TIME&MONEY v6 server on ${PORT}`));
