const http=require('http');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const PORT=Number(process.env.PORT)||3000, TURN_MS=150*1000, DAY_BATTLE_MS=30*1000, MAX_PLAYERS=50, ROOM_TTL_MS=5*60*1000, DISCONNECT_GRACE_MS=5000, MAX_BODY_BYTES=16*1024, MAX_NAME_LENGTH=20, MAX_QTY=1e12, MAX_MONEY=Number.MAX_SAFE_INTEGER, rooms=new Map(),sessions=new Map(),rate=new Map();
const ASSETS=JSON.parse(fs.readFileSync(path.join(__dirname,'session2_assets.json'),'utf8'));
const ASSET=new Map(ASSETS.map(a=>[a.id,a]));
function hash32(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
const HISTORICAL_ANCHORS={
 '005930':{1990:26600,2000:2211,2008:6534,2011:15753,2015:25200,2017:50960,2020:81000,2022:55300,2024:53200,2025:119700},
 '005490':{1990:38058,2000:33565,2008:219441,2011:232875,2015:114925,2017:243471,2020:223224,2022:250566,2024:239965,2025:301753},
 '000660':{1996:20000,2000:45000,2008:9000,2011:26000,2015:32000,2017:78000,2020:115000,2022:85000,2024:180000,2025:560000},
 'AAPL':{1990:.33,2000:.22,2008:2.55,2011:12.11,2015:23.67,2017:39.52,2020:128.82,2022:127.65,2024:248.62,2025:271.12},
 'MSFT':{1990:.60,2000:13.17,2008:14.11,2011:20.21,2015:48.27,2017:78.18,2020:212.08,2022:232.74,2024:415.78,2025:510},
 'NVDA':{1999:.35,2000:.12,2008:.18,2011:.32,2015:.80,2017:4.77,2020:12.99,2022:14.57,2024:133.94,2025:186.06},
 'BTC':{2010:.30,2011:4.70,2012:13.50,2013:754,2014:320,2015:430,2016:963,2017:14120,2018:3744,2019:7195,2020:29000,2021:46200,2022:16520,2023:42260,2024:93430,2025:87509,2026:78621},
 'GOLD_KRW':{1990:Math.round(386*700/31.1034768),2000:Math.round(279*1100/31.1034768),2008:Math.round(869*1100/31.1034768),2011:Math.round(1571*1100/31.1034768),2015:Math.round(1160*1100/31.1034768),2020:Math.round(1770*1100/31.1034768),2024:Math.round(2386*1400/31.1034768),2025:Math.round(3431*1400/31.1034768)},
 'SPY':{1993:45,2000:132,2008:90,2011:126,2015:205,2017:267,2020:373,2022:383,2024:590,2025:680},
 'QQQ':{1999:100,2000:38,2008:28,2011:58,2015:112,2017:156,2020:314,2022:267,2024:510,2025:620}
};
const HIST_MACRO={1990:1,1991:.96,1992:.90,1993:1.02,1994:1.12,1995:1.08,1996:1.04,1997:.72,1998:.63,1999:1.12,2000:1.02,2001:.82,2002:.78,2003:.94,2004:1.10,2005:1.16,2006:1.30,2007:1.38,2008:.72,2009:.94,2010:1.08,2011:1.02,2012:1.04,2013:1.08,2014:1.12,2015:1.06,2016:1.15,2017:1.30,2018:1.18,2019:1.24,2020:1.10,2021:1.30,2022:1.00,2023:1.12,2024:1.28,2025:1.42,2026:1.48};
const SECTOR_BETA={tech:1.25,finance:.9,health:1.05,energy:1.15,construction:1.05,auto:1.08,transport:1.12,materials:1.15,general:.95,global:1,crypto:2.2,gold:.45,silver:.8,oil:1.4,commodity:.8,realestate:.55,bond:.25,bondfuture:.2,fx:.35,equityfuture:1.1};
const HIST_PATH_CACHE=new Map();
function histSeed(id,key){let h=0;for(let i=0;i<String(id).length;i++)h=(h*33+String(id).charCodeAt(i))>>>0;h=(h^(key*2654435761))>>>0;return ((h%100000)/100000-.5)}
function histSector(a){const id=String(a?.id||'').toUpperCase(),name=String(a?.name||'').toLowerCase(),kind=String(a?.kind||'');if(kind==='coin')return 'crypto';if(kind==='bonds')return 'bond';if(kind==='real')return 'realestate';if(kind==='gold'){if(id.includes('SILVER'))return 'silver';if(id.includes('OIL'))return 'oil';return 'gold'}if(kind==='deriv'){if(id.startsWith('F_KTB'))return 'bond';if(id.startsWith('F_USD'))return 'global';return 'equityfuture'}if(/nvda|apple|microsoft|amazon|google|alphabet|meta|tesla|intel|amd|semiconductor|software|technology|tech|internet|game|cloud|ai/.test(id+' '+name))return 'tech';if(/bank|financial|finance|insurance|securities|card|capital/.test(id+' '+name))return 'finance';if(/oil|energy|petro|gas|refining/.test(id+' '+name))return 'energy';if(/health|pharma|bio|medical/.test(id+' '+name))return 'health';if(/auto|motor|vehicle/.test(id+' '+name))return 'auto';if(/construction|engineering|housing|realestate|developer/.test(id+' '+name))return 'construction';if(/steel|metal|chemical|material|cement/.test(id+' '+name))return 'materials';if(/transport|airline|shipping|rail/.test(id+' '+name))return 'transport';if(kind==='over'||kind==='fund')return 'global';return 'general'}
function histAnchor(id,y){const m=HISTORICAL_ANCHORS[id];if(!m)return null;if(m[y]!=null)return Number(m[y]);const ys=Object.keys(m).map(Number).sort((a,b)=>a-b),lo=ys.filter(v=>v<y).at(-1),hi=ys.find(v=>v>y);if(lo==null||hi==null)return null;const t=(y-lo)/(hi-lo);return Math.exp(Math.log(Number(m[lo]))*(1-t)+Math.log(Number(m[hi]))*t)}
function histYearFactor(a,y){const sector=histSector(a),beta=SECTOR_BETA[sector]||1,macro=HIST_MACRO[y]||1,prev=HIST_MACRO[y-1]||1;let r=Math.log(macro/prev)*beta+histSeed(a.id,y)*.08;if(y===1997)r-=.10*beta;if(y===1998)r+=.05*beta;if(y===2000&&sector==='tech')r-=.22*beta;if(y===2008&&sector!=='bond'&&sector!=='gold')r-=.30*beta;if(y===2020&&sector==='tech')r+=.08;if(y===2020&&sector==='transport')r-=.12;if(y===2021&&sector==='energy')r+=.10;if(y===2022&&sector==='tech')r-=.12;if(y===2023&&sector==='tech')r+=.08;if(y===2024&&sector==='tech')r+=.10;if(sector==='crypto'){if(y===2017)r+=1.4;if(y===2018)r-=1.2;if(y===2021)r+=.7;if(y===2022)r-=1.0}if(sector==='gold'){if(y===2008)r+=.20;if(y===2011)r+=.25;if(y===2013)r-=.22;if(y===2020)r+=.25;if(y>=2024)r+=.15}return Math.max(-.75,Math.min(1.5,r))}
function historicalUnitPrice(a,y,m){if(!a||y<a.year)return 0;let cached=HIST_PATH_CACHE.get(a.id);if(!cached){cached={};HIST_PATH_CACHE.set(a.id,cached)}const key=y*12+m;if(cached[key]!=null)return cached[key];let sy=Math.max(1990,Number(a.year)||1990),p=Number(a.ipoPrice??a.base)||1;const anchors=HISTORICAL_ANCHORS[a.id]||{};const first=Object.keys(anchors).map(Number).filter(v=>v>=sy).sort((x,z)=>x-z)[0];if(first!=null)p=Number(anchors[first]);for(let yy=sy;yy<=y;yy++){const exact=histAnchor(a.id,yy);let target=exact;if(target==null)target=p*Math.exp(histYearFactor(a,yy));const start=p,end=Number(target)||p;for(let mm=1;mm<=12;mm++){if(yy===sy&&mm===1)cached[yy*12+mm]=start;else{const t=mm/12;const v=start*Math.exp(Math.log(Math.max(end,.000001)/Math.max(start,.000001))*t+histSeed(a.id,yy*12+mm)*.012);cached[yy*12+mm]=Math.max(a.kind==='coin'?.000001:.01,v)}}p=end}return cached[key]??(Number(a.base)||1)}
function unitPrice(a,y,m){const p=historicalUnitPrice(a,y,m);return a.kind==='coin'?Number(p.toFixed(6)):Math.max(.01,Math.round(p))}
function market(room){if(!room.marketPrices)room.marketPrices={};for(const a of ASSETS)if(a.year<=room.year)room.marketPrices[a.id]=unitPrice(a,room.year,room.month);return room.marketPrices}
function positionValue(p,room){let n=0;for(const [id,q] of Object.entries(p.positions||{})){const a=ASSET.get(id),price=Number(room.marketPrices?.[id]||0);if(a&&price)n+=Number(q)*price*(Number(a.multiplier)||1)}return Math.round(n)}
function authoritativeNetWorth(p,room){return Math.round((Number(p.cash)||0)+positionValue(p,room)-(Number(p.loan)||0)-(Number(p.loanShark)||0))}
function authoritativeTotalAssets(p,room){return Math.round((Number(p.cash)||0)+positionValue(p,room))}
function syncAssetValue(p,room){p.assetValue=positionValue(p,room);p.debt=(Number(p.loan)||0)+(Number(p.loanShark)||0);return p.assetValue}
function liquidateHoldings(p,room,need){let raised=0;const holdings=Object.entries(p.positions||{}).map(([id,q])=>{const a=ASSET.get(id),price=Number(room.marketPrices?.[id]||0),unit=price*(Number(a?.multiplier)||1);return {id,a,q:Number(q)||0,price,unit,value:Math.max(0,(Number(q)||0)*unit)}}).filter(x=>x.q>0&&x.unit>0).sort((a,b)=>b.value-a.value);for(const h of holdings){if(raised+1e-9>=need)break;const target=Math.min(h.value,need-raised);const qty=Math.min(h.q,Math.floor((target/h.unit)*1000000)/1000000);if(!(qty>0))continue;const proceeds=qty*h.unit;p.cash+=proceeds;raised+=proceeds;h.q-=qty;p.positions[h.id]=h.q;if(h.q<=1e-9){delete p.positions[h.id];delete p.avg[h.id]}}syncAssetValue(p,room);return raised}
function privateState(room,p){syncAssetValue(p,room);return {cash:p.cash,positions:p.positions||{},avg:p.avg||{},loan:p.loan||0,loanShark:p.loanShark||0,sharkMonths:p.sharkMonths||0,netWorth:authoritativeNetWorth(p,room),assetValue:p.assetValue,debt:p.debt}}
const DAY_ASSETS=ASSETS.filter(a=>a&&a.kind!=='real'&&a.kind!=='bonds'&&a.kind!=='gold'&&Number(a.base)>0);
function dayAsset(room){const listed=DAY_ASSETS.filter(a=>Number(a.year||1990)<=Number(room.year||1990));return listed[crypto.randomInt(0,Math.max(1,listed.length))]||DAY_ASSETS[0];}
function dayEquity(p,price){return Math.max(0,(Number(p?.dayCash)||0)+(Number(p?.dayQty)||0)*(Number(price)||0));}
function dayTokens(p,price){return dayEquity(p,price);}
function dayView(room,p){const d=room.dayBattle||{};const price=Number(d.price)||0,initial=Math.max(1,Number(p?.dayInitial)||100),equity=dayEquity(p,price),pct=((equity-initial)/initial)*100;return {active:!!d.active,assetId:d.assetId||null,assetName:d.assetName||null,unit:d.unit||'',currentPrice:price,endAt:Number(d.deadline)||0,serverNow:Date.now(),history:Array.isArray(d.history)?d.history.slice(-180):[],myQty:Number(p?.dayQty)||0,myCost:Number(p?.dayCost)||0,myEquity:Math.round(equity),myInitial:initial,myPct:Number.isFinite(pct)?pct:0,myUnrealized:Math.round(equity-initial),winner:d.winner||null,loser:d.loser||null,winnerTokens:d.winnerTokens??null,loserTokens:d.loserTokens??null,settled:!!d.settled};}
function tickDayBattle(room){if(!room.dayBattle?.active)return;const d=room.dayBattle;const p=Math.max(.000001,Number(d.price)||.000001),a=ASSET.get(d.assetId);const vol=Math.max(.004,Math.min(.035,Number(a?.vol)||.012));const next=Math.max(.000001,p*(1+((crypto.randomInt(-100,101)/10000)*Math.sqrt(vol/.012))));d.price=a?.kind==='coin'?Number(next.toFixed(6)):Math.max(.01,Math.round(next*100)/100);d.history=Array.isArray(d.history)?d.history:[];d.history.push({t:Date.now(),p:d.price});if(d.history.length>180)d.history=d.history.slice(-180);for(const pl of room.players.values())pl.dayPct=0;}
function securityHeaders(req){const h={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin','X-Permitted-Cross-Domain-Policies':'none','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'"};if(String(req.headers['x-forwarded-proto']||'').split(',')[0].trim()==='https'||req.socket.encrypted)h['Strict-Transport-Security']='max-age=31536000; includeSubDomains';return h}
function json(res,status,obj,req=null){const body=JSON.stringify(obj);const h={'Content-Type':'application/json; charset=utf-8',...securityHeaders(req||{headers:{},socket:{}})};res.writeHead(status,h);res.end(body)}
function ip(req){return (req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim()}
function limited(req,route='global'){const limit=route==='create'||route==='join'?12:route==='trade'||route==='loan'||route==='liquidate'||route==='daytrade'?120:route==='poll'?180:240,now=Date.now();const hit=(key,max)=>{const x=rate.get(key)||{t:now,n:0};if(now-x.t>60000){x.t=now;x.n=0}x.n++;rate.set(key,x);return x.n>max};if(hit(ip(req)+'|'+route,limit))return true;const h=String(req.headers.authorization||'');if(/^Bearer [0-9a-f]{64}$/i.test(h)&&hit('s:'+h.slice(7)+'|'+route,limit))return true;return false}
function token(){return crypto.randomBytes(32).toString('hex')}
function roomCode(){let c;do c=String(crypto.randomInt(0,1000000)).padStart(6,'0');while(rooms.has(c));return c}
function safeName(n){const v=String(n??'Player').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,MAX_NAME_LENGTH);return v||'Player'}
function validRoomCode(v){return /^\d{6}$/.test(String(v||''))}
function sessionTokenFrom(req,b={}){const h=String(req.headers.authorization||'');if(/^Bearer [0-9a-f]{64}$/i.test(h))return h.slice(7);const t=String(b.sessionToken||'');return /^[0-9a-f]{64}$/i.test(t)?t:''}
function finiteNumber(v,min=-MAX_MONEY,max=MAX_MONEY){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function validQty(v){const n=finiteNumber(v,0,MAX_QTY);if(n===null||n<=0)return null;return Math.floor(n*1000000)/1000000}
function netWorth(p){return Math.round((Number(p.cash)||0)+(Number(p.assetValue)||0)-(Number(p.debt)||0))}
function debtExcludedWealth(p,room){return Math.round((Number(p.cash)||0)+positionValue(p,room))}
function markAutoReadyIfBroke(room){if(!room.started||room.finished||room.dayBattle?.active)return false;let changed=false;for(const p of room.players.values()){if(!p.ready&&debtExcludedWealth(p,room)<=0){p.ready=true;p.autoReady=true;p.autoReadyReason='무부채 재산 0원 이하';changed=true}}return changed}
function markDisconnectedReady(room,now=Date.now()){if(!room.started||room.finished||room.dayBattle?.active)return false;let changed=false;for(const p of room.players.values()){if(!p.ready&&!p.left&&p.lastSeen&&now-p.lastSeen>=DISCONNECT_GRACE_MS){p.ready=true;p.autoReady=true;p.autoReadyReason='접속 끊김 자동 승인';p.disconnected=true;changed=true}}return changed}
function maybeAdvance(room){if(!room.started||room.finished||room.dayBattle?.active)return {advanced:false,finished:false};markAutoReadyIfBroke(room);markDisconnectedReady(room);if([...room.players.values()].every(x=>x.ready))return advance(room);return {advanced:false,finished:false,readyCount:[...room.players.values()].filter(x=>x.ready).length}}
function periodFor(y,m){const startMonth=((m-1)%6)+1;const startM=m-startMonth+1;const sy=y;const ey=y,em=Math.min(startM+5,12);return {start:{year:sy,month:startM},end:{year:ey,month:em}}}
function activateCountdown(room){if(room.startAt && !room.started && Date.now()>=room.startAt){room.startAt=0;startRoom(room);return true}return false}
function view(room,playerId){activateCountdown(room);for(const x of room.players.values())syncAssetValue(x,room);markAutoReadyIfBroke(room);markDisconnectedReady(room);if(room.dayBattle?.active&&Date.now()>=room.dayBattle.deadline)finishDayBattle(room);const p=playerId?room.players.get(playerId):null;const dayBattleLeaderboard=[...room.players.values()].filter(x=>!x.left).map(x=>({name:x.name,tokens:room.dayBattle?.active?Number(dayTokens(x,Number(room.dayBattle.price)||0).toFixed(2)):null})).sort((a,b)=>(b.tokens??-Infinity)-(a.tokens??-Infinity)).map((x,i)=>({name:x.name,rank:i+1}));return {roomCode:room.code,hostId:room.hostId,started:room.started,finished:room.finished,startAt:room.startAt||0,countdownActive:!!(room.startAt&&!room.started),year:room.year,month:room.month,turn:room.turn||0,deadline:room.deadline,turnDeadline:room.turnDeadline||room.deadline,periodStart:room.periodStart,periodEnd:room.periodEnd,playerCount:room.players.size,readyCount:[...room.players.values()].filter(x=>x.ready).length,meReady:!!p?.ready,canStart:room.players.size>=2&&room.hostId===playerId&&!room.started&&!room.finished,players:[...room.players.values()].filter(x=>!x.left).map(x=>({id:x.id,name:x.name,ready:!!x.ready,autoReady:!!x.autoReady,autoReadyReason:x.autoReadyReason||'',netWorth:authoritativeNetWorth(x,room),totalAssets:authoritativeTotalAssets(x,room)})),dayBattle:room.dayBattle||{active:false},onlineNews:room.onlineNews||null,onlineEvent:room.onlineEvent||null,dayBattleLeaderboard,leaderboard:[...room.players.values()].filter(x=>!x.left).map(x=>({name:x.name,netWorth:authoritativeNetWorth(x,room)})).sort((a,b)=>b.netWorth-a.netWorth),market:{prices:room.marketPrices||market(room)},turnPlayerId:room.turnPlayerId||null,me:p?privateState(room,p):null,dayTrade:dayView(room,p)}}
function body(req){return new Promise((resolve,reject)=>{const declared=Number(req.headers['content-length']||0);if(declared>MAX_BODY_BYTES){reject(Object.assign(new Error('payload too large'),{status:413}));return}let s='',done=false;const fail=(e)=>{if(done)return;done=true;reject(e)};req.on('data',c=>{s+=c;if(s.length>MAX_BODY_BYTES){req.destroy();fail(Object.assign(new Error('payload too large'),{status:413}))}});req.on('end',()=>{if(done)return;try{done=true;resolve(s?JSON.parse(s):{})}catch(e){fail(e)}});req.on('error',fail)})}
function auth(room,t){const s=sessions.get(t);if(!s||s.room!==room.code||s.exp<Date.now()){if(s&&s.exp<Date.now())sessions.delete(t);return null}const p=room.players.get(s.id)||null;if(p){p.lastSeen=Date.now();p.disconnected=false;if(!p.left)room.emptySince=0}return p}
function historicalOnlineEventForDate(y,m){
  const k=Number(y)*12+Number(m);
  const H=(start,end,title,text,sector,rate,cash=0)=>({start,end,title,text,sector,rate,cash});
  const events=[
    H(1997*12+11,1998*12+3,'1997.11~1998.03 외환위기','1997년 11월 원화 방어가 무너지고 12월 4일 IMF 지원이 결정됐습니다. 12월 24일 원/달러 환율은 약 1,965원까지 치솟았고 KOSPI는 351까지 하락했습니다.','crisis',-0.12,200000),
    H(2000*12+3,2000*12+12,'2000 닷컴 버블 붕괴','인터넷·기술주 거품이 붕괴하면서 성장주와 관련 펀드의 위험선호가 급격히 약해졌습니다.','tech',-0.10,100000),
    H(2001*12+9,2001*12+12,'2001 9·11 충격','9·11 테러 이후 글로벌 증시와 항공·운송업종의 위험회피가 커졌습니다.','riskoff',-0.06,100000),
    H(2003*12+3,2003*12+6,'2003 SARS 확산','SARS 확산으로 운송·소비가 위축되고 일부 헬스케어 수요가 늘었습니다.','sars',-0.05,100000),
    H(2008*12+9,2009*12+3,'2008 글로벌 금융위기','2008년 9월 리먼브러더스 파산 뒤 신용경색이 확대되며 금융주와 경기민감 자산이 급락했습니다.','gfc',-0.15,200000),
    H(2011*12+8,2011*12+10,'2011 미국 신용등급 강등·유럽 재정위기','글로벌 위험회피가 강해지며 주식시장이 흔들리고 안전자산 선호가 커졌습니다.','debt',-0.05,100000),
    H(2015*12+8,2015*12+10,'2015 중국 경기둔화·증시 급락','중국 경기둔화 우려와 글로벌 증시 급락으로 원자재·수출 관련 위험이 커졌습니다.','china',-0.05,100000),
    H(2017*12+11,2017*12+12,'2017 가상자산 과열','가상자산 투기 수요가 급격히 커지며 가격이 과열됐습니다.','crypto',0.18,100000),
    H(2018*12+1,2018*12+12,'2018 가상자산 급락','가상자산 과열이 꺼지며 주요 코인 가격이 크게 조정됐습니다.','crypto',-0.20,100000),
    H(2020*12+3,2020*12+6,'2020 코로나19 충격','코로나19 확산과 봉쇄로 운송·소비가 급격히 위축됐고 기술주·안전자산으로 자금이 이동했습니다.','covid',-0.12,200000),
    H(2021*12+1,2021*12+6,'2021 유동성 장세','저금리와 유동성 확대로 성장주와 가상자산에 강한 위험선호가 나타났습니다.','liquidity',0.08,100000),
    H(2022*12+1,2022*12+12,'2022 급격한 금리인상','인플레이션 대응을 위한 빠른 금리인상으로 성장주·가상자산과 장기채가 압박을 받았습니다.','rates',-0.08,100000)
  ];
  const hit=events.find(e=>k>=e.start&&k<=e.end);if(hit)return hit;
  const regimes={1990:['1990년대 초 경기·금리 변동','당시 국내 경기와 금리 변화가 주식·채권 시장의 위험선호를 좌우했습니다.','broad',0.02],1991:['1991 경기 둔화','경기 둔화와 금리 흐름이 위험자산 상승 탄력을 제한했습니다.','broad',-0.015],1992:['1992 금융시장 개방 전후','자본시장 변화와 경기 흐름이 국내외 투자심리에 영향을 줬습니다.','broad',0.01],1993:['1993 경기 회복','경기 회복 기대가 위험자산 선호를 점차 높였습니다.','broad',0.02],1994:['1994 성장 가속','고성장 국면에서 기업 실적 기대가 높아졌습니다.','broad',0.03],1995:['1995 수출·제조업 호조','수출과 제조업 투자 확대가 경기민감 업종에 우호적이었습니다.','cyclical',0.025],1996:['1996 경기 둔화','반도체 경기와 내수 둔화가 위험자산에 부담을 줬습니다.','tech',-0.025],1999:['1999 외환위기 이후 회복 랠리','구조조정과 경기 회복 기대가 주식시장 위험선호를 되살렸습니다.','broad',0.04],2002:['2002 경기 회복','내수 회복과 IT 투자 확대로 위험자산 선호가 살아났습니다.','broad',0.03],2004:['2004 수출 회복','수출 회복과 글로벌 경기 개선이 경기민감 자산에 우호적이었습니다.','cyclical',0.025],2005:['2005 자산시장 활황','국내 자산시장에 대한 위험선호가 강해졌습니다.','realestate',0.03],2006:['2006 글로벌 경기 호조','글로벌 경기 확장으로 주식·원자재 선호가 이어졌습니다.','cyclical',0.03],2007:['2007 금융시장 호황','글로벌 유동성과 기업이익 기대가 위험자산 가격을 끌어올렸습니다.','broad',0.025],2009:['2009 금융위기 이후 반등','정책 대응과 유동성 공급으로 글로벌 위험자산이 반등했습니다.','broad',0.04],2010:['2010 경기 회복','글로벌 경기 회복으로 위험자산 선호가 개선됐습니다.','broad',0.025],2012:['2012 유럽위기 완화','유럽 재정위기 우려가 완화되며 위험자산이 안정됐습니다.','broad',0.015],2013:['2013 출구전략 우려','미국 통화정책 전환 우려가 신흥시장 변동성을 높였습니다.','global',-0.02],2014:['2014 저금리·원자재 하락','저금리 환경은 위험자산에 우호적이었지만 원자재 가격은 약세였습니다.','oil',-0.025],2016:['2016 브렉시트·정책 불확실성','브렉시트 충격 이후 안전자산 선호와 정책 불확실성이 공존했습니다.','riskoff',-0.02],2019:['2019 미중 무역갈등','무역갈등이 제조·수출주와 글로벌 투자심리에 부담을 줬습니다.','global',-0.025],2023:['2023 금리 고점과 AI 기대','고금리 부담 속에서도 AI·반도체 성장 기대가 기술주를 지지했습니다.','tech',0.035],2024:['2024 AI·반도체 투자 확대','AI와 반도체 투자 기대가 기술·성장주에 강한 관심을 만들었습니다.','tech',0.04],2025:['2025 기술주·금리 불확실성','기술주 성장 기대와 금리·정책 불확실성이 동시에 시장을 움직였습니다.','tech',0.02],2026:['2026 시장 변동성','금리와 글로벌 성장 전망 변화가 자산별 차별화를 키웠습니다.','broad',0.015]};
  const r=regimes[y]||['당시 경기·금융시장 환경','당시의 거시경제 환경을 반영한 시장 변동입니다.','broad',0.01];return H(k,k,r[0],r[1],r[2],r[3],0);
}
function onlineAssetSector(a){const id=String(a?.id||'').toUpperCase(),name=String(a?.name||'').toLowerCase(),kind=String(a?.kind||'');if(kind==='coin')return 'crypto';if(kind==='bonds')return 'bond';if(kind==='real')return 'realestate';if(kind==='gold'){if(id.includes('SILVER'))return 'silver';if(id.includes('OIL'))return 'oil';return 'gold'}if(kind==='deriv'){if(id.startsWith('F_KTB'))return 'bond';if(id.startsWith('F_USD'))return 'global';return 'equityfuture'}if(/nvda|apple|microsoft|amazon|google|alphabet|meta|tesla|intel|amd|semiconductor|software|technology|tech|internet|game|cloud|ai/.test(id+' '+name))return 'tech';if(/bank|financial|finance|insurance|securities|card|capital/.test(id+' '+name))return 'finance';if(/oil|energy|petro|gas|refining/.test(id+' '+name))return 'energy';if(/health|pharma|bio|medical/.test(id+' '+name))return 'health';if(/auto|motor|vehicle/.test(id+' '+name))return 'auto';if(/construction|engineering|housing|realestate|developer/.test(id+' '+name))return 'construction';if(/steel|metal|chemical|material|cement/.test(id+' '+name))return 'materials';if(/transport|airline|shipping|rail/.test(id+' '+name))return 'transport';if(kind==='over'||kind==='fund')return 'global';return 'general'}
function onlineHistoricalFilter(sector){return a=>{const s=onlineAssetSector(a);if(sector==='broad')return s!=='crypto';if(['crisis','gfc','debt','riskoff'].includes(sector))return ['tech','finance','construction','auto','transport','materials','energy','general','global','equityfuture','realestate'].includes(s);if(sector==='tech')return ['tech','global'].includes(s);if(sector==='sars')return ['transport','health','global'].includes(s);if(['china','cyclical'].includes(sector))return ['materials','energy','auto','transport','global','general'].includes(s);if(sector==='crypto')return s==='crypto';if(sector==='covid')return ['general','global','transport','construction','realestate'].includes(s);if(sector==='liquidity')return ['tech','global','crypto'].includes(s);if(sector==='rates')return ['tech','crypto','bond'].includes(s);if(sector==='realestate')return s==='realestate';if(sector==='oil')return ['oil','energy'].includes(s);if(sector==='global')return ['global','tech','general'].includes(s);return true}}
function onlineEventOverlay(a,e){const s=histSector(a),k=e?.sector||'broad';const profiles={crisis:{finance:-.06,construction:-.045,auto:-.035,materials:-.035,transport:-.03,tech:-.025,realestate:-.02,bond:-.01,gold:.025},tech:{tech:-.08,global:-.045,general:-.025},riskoff:{transport:-.05,finance:-.04,tech:-.03,gold:.025,bond:.015},sars:{transport:-.08,global:-.025,health:.03},gfc:{finance:-.08,construction:-.06,auto:-.05,transport:-.045,tech:-.04,realestate:-.035,gold:.035,bond:.02},debt:{finance:-.04,tech:-.035,global:-.03,gold:.02,bond:.015},china:{materials:-.06,energy:-.05,auto:-.035,transport:-.025,global:-.02},crypto:{crypto:Number(e?.rate)||0},covid:{transport:-.08,realestate:-.045,construction:-.04,general:-.035,global:-.025,tech:.035,gold:.025},liquidity:{tech:.055,global:.035,crypto:.08},rates:{tech:-.06,crypto:-.08,bond:-.035,bondfuture:-.03,gold:-.015},realestate:{realestate:Number(e?.rate)||.03},oil:{oil:Number(e?.rate)||-.025,energy:(Number(e?.rate)||-.025)*.65},global:{global:Number(e?.rate)||-.02,tech:(Number(e?.rate)||-.02)*.8,general:(Number(e?.rate)||-.02)*.6},broad:{general:Number(e?.rate)||.01,global:(Number(e?.rate)||.01)*.8,tech:(Number(e?.rate)||.01)*.75,bond:(Number(e?.rate)||.01)*.2,gold:(Number(e?.rate)||.01)*.3}};return Number(profiles[k]?.[s]??0)}
function applyOnlineHistoricalMarketEvent(room,e){let changed=0;for(const a of ASSETS){if(Number(a.year)>Number(room.year))continue;const overlay=onlineEventOverlay(a,e);if(!overlay)continue;const p=Number(room.marketPrices?.[a.id]||0);if(!(p>0))continue;const np=a.kind==='coin'?Number(Math.max(.000001,p*(1+overlay)).toFixed(6)):Math.max(.01,Math.round(p*(1+overlay)));room.marketPrices[a.id]=np;changed++}e.changed=changed;return changed}
function moneyWon(v){return `₩${Math.round(Number(v)||0).toLocaleString('ko-KR')}`}
function onlineTurnContent(room){const e=historicalOnlineEventForDate(room.year,room.month);room.onlineNews={category:'역사',title:e.title,text:e.text,year:room.year,month:room.month};room.onlineEvent={kind:'역사적 시장',title:e.title,text:`${e.text} 게임에서는 당시 충격이 컸던 투자군을 중심으로 역사적 방향에 맞는 섹터별 가격 오버레이를 적용합니다.${e.cash?` 현금 지출은 ${moneyWon(e.cash)}로 제한됩니다.`:''}`,sector:e.sector,rate:e.rate,cap:200000,cashCost:Math.min(200000,Math.max(0,Number(e.cash)||0)),applied:false};applyOnlineHistoricalMarketEvent(room,room.onlineEvent)}
function applyOnlineEvent(room){const e=room.onlineEvent;if(!e||e.applied)return false;for(const p of room.players.values()){const cost=Math.min(200000,Math.max(0,Number(e.cashCost)||0));if(cost>0)p.cash=Math.max(0,Number(p.cash||0)-cost);syncAssetValue(p,room)}e.applied=true;e.appliedAt=Date.now();return true}
function maybeDayBattle(room){room.dayBattle={active:false,startedAt:0,deadline:0,pausedMs:0};if(room.players.size<2)return;if(room.year===1990&&room.month===1)return;if(crypto.randomInt(0,100)<15){const remaining=Math.max(0,(room.turnDeadline||room.deadline)-Date.now());room.turnRemainingMs=remaining;room.deadline=0;const a=dayAsset(room);const marketPrice=Number(room.marketPrices?.[a.id]||unitPrice(a,room.year,room.month)||a.base||1);room.dayBattle={active:true,startedAt:Date.now(),deadline:Date.now()+DAY_BATTLE_MS,pausedMs:remaining,assetId:a.id,assetName:a.name,unit:a.unit||'단위',price:marketPrice,history:[{t:Date.now(),p:marketPrice}],winner:null,loser:null,settled:false};for(const p of room.players.values()){p.dayBudget=100;p.dayInitial=100;p.dayCash=100;p.dayQty=0;p.dayCost=0;p.dayPct=0;p.dayTradePnl=0;p.dayReady=false;}}}
function startRoom(room){if(room.started||room.finished||room.players.size<2)return false;room.startAt=0;room.started=true;room.year=1990;room.month=1;room.turn=0;room.periodStart={year:1990,month:1};room.periodEnd={year:1990,month:6};room.turnPlayerId=null;market(room);room.deadline=Date.now()+TURN_MS;room.turnDeadline=room.deadline;room.turnRemainingMs=TURN_MS;room.dayBattle={active:false,startedAt:0,deadline:0,pausedMs:0};for(const p of room.players.values()){p.ready=false;p.autoReady=false;p.autoReadyReason='';p.disconnected=false;p.left=false;p.lastSeen=Date.now()}return true}
function advance(room){if(room.finished)return {advanced:false,finished:true};if(room.year===2026&&room.month===7){room.periodStart={year:2026,month:7};room.periodEnd={year:2026,month:12};room.year=2026;room.month=12;room.finished=true;room.finishedAt=Date.now();room.deadline=0;room.turnDeadline=0;room.turnRemainingMs=0;for(const p of room.players.values())p.ready=false;return {advanced:false,finished:true}}room.month+=6;if(room.month>12){room.month-=12;room.year++}if(room.year>2026||(room.year===2026&&room.month>7)){room.finished=true;room.deadline=0;room.turnDeadline=0;room.turnRemainingMs=0;for(const p of room.players.values())p.ready=false;return {advanced:false,finished:true}}room.turn=(Number(room.turn)||0)+1;room.periodStart={year:room.year,month:room.month};room.periodEnd=periodFor(room.year,room.month).end;for(const p of room.players.values()){p.ready=false;p.autoReady=false;p.autoReadyReason='';if(p.loan)p.loan=Math.round(p.loan*Math.pow(1.01,6));if(p.loanShark){p.loanShark=Math.round(p.loanShark*Math.pow(1.05,6));p.sharkMonths=(Number(p.sharkMonths)||0)+6}else p.sharkMonths=0;if(p.sharkMonths>=12&&p.loanShark>0){p.cash=0;p.positions={};p.avg={};p.loanShark=0;p.sharkMonths=0;p.autoReady=true;p.autoReadyReason='사채 12개월 미상환 — 재산 몰수';}syncAssetValue(p,room)}market(room);room.deadline=Date.now()+TURN_MS;room.turnDeadline=room.deadline;room.turnRemainingMs=TURN_MS;onlineTurnContent(room);maybeDayBattle(room);if(!room.dayBattle?.active)applyOnlineEvent(room);else room.onlineEvent.pendingUntilDayBattleEnd=true;return {advanced:true,finished:false}}
function finishDayBattle(room){if(!room.dayBattle?.active)return;if(Date.now()<room.dayBattle.deadline)return;const active=[...room.players.values()].filter(x=>!x.left);const price=Number(room.dayBattle.price)||0;for(const p of active){if(Number(p.dayQty)>0){p.dayCash+=Number(p.dayQty)*price;p.dayQty=0;p.dayCost=0}p.dayTradePnl=Math.round(Number(p.dayCash||0)-(Number(p.dayInitial)||100));p.dayPct=((Number(p.dayCash||0)-(Number(p.dayInitial)||100))/Math.max(1,Number(p.dayInitial)||100))*100}const ranked=active.map(x=>({p:x,tokens:Math.max(0,Number(x.dayCash)||0)})).sort((a,b)=>b.tokens-a.tokens);const tied=ranked.length>1&&Math.abs(ranked[0].tokens-ranked[1].tokens)<0.000001;const first=tied?null:ranked[0]?.p;const firstTokens=ranked[0]?.tokens??null;const loserTokens=ranked.length>1?ranked[ranked.length-1].tokens:null;const beforeFirst=first?Math.max(0,authoritativeTotalAssets(first,room)):0;if(first)first.cash+=Math.round(beforeFirst*.5);if(first)syncAssetValue(first,room);const paused=Math.max(0,Number(room.dayBattle.pausedMs)||0);room.dayBattle={...room.dayBattle,active:false,winner:first?.name||null,loser:ranked.length>1?ranked[ranked.length-1].p.name:null,pausedMs:paused,settled:true,tie:tied,winnerTokens:firstTokens,loserTokens:loserTokens,settledAt:Date.now()};if(room.onlineEvent?.pendingUntilDayBattleEnd){delete room.onlineEvent.pendingUntilDayBattleEnd;applyOnlineEvent(room)}room.deadline=Date.now()+paused;room.turnDeadline=room.deadline;room.turnRemainingMs=paused;active.forEach(x=>{x.dayPct=undefined;x.dayReady=false;x.dayBudget=0;x.dayInitial=0;x.dayCash=0;x.dayQty=0;x.dayCost=0})}
function create(name){const code=roomCode();const id=crypto.randomUUID(),t=token();const room={code,hostId:id,year:1990,month:1,deadline:0,periodStart:{year:1990,month:1},periodEnd:{year:1990,month:6},started:false,finished:false,createdAt:Date.now(),finishedAt:0,players:new Map(),dayBattle:{active:false,startedAt:0,deadline:0}};rooms.set(code,room);room.players.set(id,{id,name:safeName(name),cash:100000000,assetValue:0,debt:0,positions:{},avg:{},loan:0,loanShark:0,sharkMonths:0,ready:false,dayReady:false,lastSeen:Date.now()});sessions.set(t,{room:code,id,exp:Date.now()+86400000});return {token:t,id,code}}
async function handler(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);const route=req.method==='GET'&&u.pathname.startsWith('/api/rooms/')?'poll':u.pathname.startsWith('/api/rooms/')?u.pathname.split('/').pop()||'rooms':u.pathname==='/api/rooms'?'create':'global';if(limited(req,route))return json(res,429,{error:'요청이 너무 많습니다. 잠시 후 다시 시도하세요.'},req);if(req.method==='GET'&&u.pathname==='/'){const h={'Content-Type':'text/html; charset=utf-8',...securityHeaders(req)};res.writeHead(200,h);return fs.createReadStream(path.join(__dirname,'index.html')).pipe(res)}
try{
if(req.method==='POST'&&u.pathname==='/api/rooms'){const b=await body(req);if(b.name!==undefined&&typeof b.name!=='string')return json(res,400,{error:'이름이 잘못되었습니다.'},req);const r=create(b.name);return json(res,200,{roomCode:r.code,sessionToken:r.token,playerId:r.id,started:false,year:1990,month:1,deadline:0,periodStart:{year:1990,month:1},periodEnd:{year:1990,month:6}})}
if(req.method==='POST'&&u.pathname==='/api/rooms/join'){const b=await body(req);if(!validRoomCode(b.roomCode)||typeof b.name!=='string'&&b.name!==undefined)return json(res,400,{error:'방 코드 또는 이름이 잘못되었습니다.'},req);const room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});if(room.finished)return json(res,409,{error:'이미 종료된 방입니다.'});if(room.started)return json(res,409,{error:'이미 시작된 방입니다.'});if(room.players.size>=MAX_PLAYERS)return json(res,409,{error:'방이 가득 찼습니다.'});const id=crypto.randomUUID(),t=token();room.players.set(id,{id,name:safeName(b.name),cash:100000000,assetValue:0,debt:0,positions:{},avg:{},loan:0,loanShark:0,sharkMonths:0,ready:false,dayReady:false,lastSeen:Date.now()});sessions.set(t,{room:room.code,id,exp:Date.now()+86400000});return json(res,200,{...view(room,id),sessionToken:t,playerId:id})}
if(req.method==='POST'&&u.pathname==='/api/rooms/start'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(room.hostId!==p.id)return json(res,403,{error:'방장만 대전을 시작할 수 있습니다.'});if(room.players.size<2)return json(res,409,{error:'최소 2명이 필요합니다.'});if(room.started)return json(res,409,{error:'이미 시작된 대전입니다.'});if(!startRoom(room))return json(res,409,{error:'대전을 시작할 수 없습니다.'});return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/progress'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});const pl=room.players.get(p.id);if(!pl)return json(res,401,{error:'플레이어를 찾을 수 없습니다.'});if(!room.started)return json(res,409,{error:'아직 대전이 시작되지 않았습니다.'});if(room.finished)return json(res,200,{...view(room,p.id),finished:true});markAutoReadyIfBroke(room);if(pl.ready)return json(res,200,{...view(room,p.id),alreadyReady:true});pl.ready=true;pl.autoReady=false;pl.autoReadyReason='';let result={advanced:false,finished:false};if(!room.dayBattle?.active)result=maybeAdvance(room);return json(res,200,{...view(room,p.id),...result})}
if(req.method==='POST'&&u.pathname==='/api/rooms/trade'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'진행 중인 대전이 아닙니다.'});const a=ASSET.get(String(b.assetId||'')),side=b.side,qty=validQty(b.qty);if(!a||!['buy','sell'].includes(side)||qty===null)return json(res,400,{error:'잘못된 거래입니다.'});if(a.year>room.year)return json(res,409,{error:'아직 거래할 수 없는 자산입니다.'});const price=Number(room.marketPrices?.[a.id]||0),unit=price*(Number(a.multiplier)||1),value=qty*unit;if(!price||!Number.isFinite(value))return json(res,409,{error:'시장 가격을 확인할 수 없습니다.'});const owned=Number(p.positions?.[a.id]||0);if(side==='buy'){if(Number(p.cash)<value)return json(res,409,{error:'현금이 부족합니다.',shortage:true,required:value,available:Number(p.cash)||0});const old=owned,oldAvg=Number(p.avg?.[a.id]||0);p.cash-=value;p.positions[a.id]=old+qty;p.avg[a.id]=old?((oldAvg*old)+value)/(old+qty):value}else{if(owned<qty)return json(res,409,{error:'보유 수량이 부족합니다.'});p.cash+=value;p.positions[a.id]=owned-qty;if(!p.positions[a.id]){delete p.positions[a.id];delete p.avg[a.id]}}syncAssetValue(p,room);return json(res,200,{...view(room,p.id),trade:{assetId:a.id,side,qty,value,price}})}
if(req.method==='POST'&&u.pathname==='/api/rooms/loan'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'진행 중인 대전이 아닙니다.'});const kind=b.kind==='shark'?'shark':'bank',amount=finiteNumber(b.amount,1,MAX_MONEY);if(amount===null||!Number.isInteger(amount)||amount<1)return json(res,400,{error:'대출 금액이 잘못되었습니다.'});syncAssetValue(p,room);const nw=Math.max(0,authoritativeNetWorth(p,room)),max=kind==='bank'?Math.floor(nw*1.5):Math.floor(nw*4),used=kind==='bank'?Number(p.loan)||0:Number(p.loanShark)||0,v=Math.min(amount,Math.max(0,max-used));if(v<1)return json(res,409,{error:'대출 한도가 없습니다. 현재 순자산이 0원 이하입니다.'});if(kind==='bank')p.loan=(Number(p.loan)||0)+v;else p.loanShark=(Number(p.loanShark)||0)+v;p.cash+=v;syncAssetValue(p,room);return json(res,200,{...view(room,p.id),loaned:v,kind})}
if(req.method==='POST'&&u.pathname==='/api/rooms/repay'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'상환할 수 없는 대전 상태입니다.'});const kind=b.kind==='shark'?'shark':'bank',amount=finiteNumber(b.amount,1,MAX_MONEY);if(amount===null||!Number.isInteger(amount)||amount<1)return json(res,400,{error:'상환 금액이 잘못되었습니다.'});const key=kind==='bank'?'loan':'loanShark',debt=Math.max(0,Number(p[key])||0),v=Math.min(amount,debt,Math.max(0,Number(p.cash)||0));if(v<1)return json(res,409,{error:'상환 가능한 현금 또는 원금이 없습니다.'});p[key]=debt-v;p.cash-=v;if(kind==='shark'&&p.loanShark<=0)p.sharkMonths=0;syncAssetValue(p,room);return json(res,200,{...view(room,p.id),repaid:v,kind})}
if(req.method==='POST'&&u.pathname==='/api/rooms/liquidate'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});const requested=finiteNumber(b.amount,1,MAX_MONEY),need=requested===null?0:Math.ceil(requested);if(!room.started||room.finished||need<1)return json(res,409,{error:'매도할 수 없습니다.'});let raised=0;const holdings=Object.entries(p.positions||{}).map(([id,q])=>{const a=ASSET.get(id),price=Number(room.marketPrices?.[id]||0),unit=price*(Number(a?.multiplier)||1);return {id,a,q:Number(q)||0,price,unit,value:Math.max(0,Math.round((Number(q)||0)*unit))}}).filter(x=>x.q>0&&x.price>0).sort((a,b)=>b.value-a.value);for(const h of holdings){if(raised>=need)break;const target=Math.min(h.value,need-raised);const qty=Math.min(h.q,Math.floor((target/h.unit)*1000000)/1000000);const proceeds=Math.min(h.value,qty*h.unit);p.cash+=proceeds;raised+=proceeds;p.positions[h.id]=h.q-qty;if(p.positions[h.id]<=0){delete p.positions[h.id];delete p.avg[h.id]}}syncAssetValue(p,room);if(raised<need)return json(res,409,{error:'보유 투자물을 모두 매도해도 부족 금액을 마련할 수 없습니다.',raised,required:need,shortage:true});return json(res,200,{...view(room,p.id),liquidated:raised,required:need})}
if(req.method==='POST'&&u.pathname==='/api/rooms/score'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'},req);const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'},req);return json(res,200,{...view(room,p.id),serverAuthoritative:true},req)}
if(req.method==='POST'&&u.pathname==='/api/rooms/daytrade'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished||!room.dayBattle?.active)return json(res,409,{error:'진행 중인 전체참여 단타가 없습니다.'});const pl=room.players.get(p.id),side=b.side==='sell'?'sell':'buy',price=Number(room.dayBattle.price)||0;if(!(price>0))return json(res,409,{error:'단타 시장 가격을 확인할 수 없습니다.'});if(side==='buy'){const cash=Math.max(0,Number(pl.dayCash)||0);if(cash<=0)return json(res,409,{error:'사용 가능한 단타 토큰이 없습니다.'});const qty=cash/price;pl.dayQty=qty;pl.dayCost=cash;pl.dayCash=0}else{const qty=Math.max(0,Number(pl.dayQty)||0);if(qty<=0)return json(res,409,{error:'보유 단타 자산이 없습니다.'});pl.dayCash+=qty*price;pl.dayQty=0;pl.dayCost=0}return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/daybattle/score'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(!room.dayBattle?.active)return json(res,409,{error:'진행 중인 전체참여 단타가 없습니다.'});const pl=room.players.get(p.id);return json(res,200,view(room,p.id))}
if(req.method==='POST'&&u.pathname==='/api/rooms/force-progress'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(room.hostId!==p.id)return json(res,403,{error:'방장만 턴을 강제로 넘길 수 있습니다.'});if(!room.started||room.finished)return json(res,409,{error:'강제 진행할 수 없는 상태입니다.'});if(room.dayBattle?.active)return json(res,409,{error:'전체참여 단타가 끝난 뒤 강제 진행할 수 있습니다.'});for(const x of room.players.values()){x.ready=false;x.autoReady=false;x.autoReadyReason='';}const result=advance(room);return json(res,200,{...view(room,p.id),...result,forcedByHost:true})}
if(req.method==='POST'&&u.pathname==='/api/rooms/leave'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,sessionTokenFrom(req,b));if(!p)return json(res,401,{error:'인증 실패'});if(room.started&&!room.finished){p.ready=true;p.autoReady=true;p.autoReadyReason='플레이어 퇴장 자동 승인';p.left=true;p.disconnected=true;p.lastSeen=Date.now();sessions.delete(sessionTokenFrom(req,b));if(room.hostId===p.id){const next=[...room.players.values()].find(x=>x.id!==p.id&&!x.left);room.hostId=next?.id||null}const result=maybeAdvance(room);return json(res,200,{ok:true,autoReady:true,...result})}room.players.delete(p.id);sessions.delete(sessionTokenFrom(req,b));if(room.hostId===p.id){const next=room.players.values().next().value;room.hostId=next?.id||null;room.startAt=0}if(room.players.size===0)room.emptySince=Date.now();return json(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname.startsWith('/api/rooms/')){const code=u.pathname.split('/').pop(),room=rooms.get(code),t=sessionTokenFrom(req,{});if(!validRoomCode(code)||!room||!auth(room,t))return json(res,401,{error:'인증 실패'});const p=auth(room,t);if(room.started&&!room.finished&&!room.dayBattle?.active&&Date.now()>=room.deadline){advance(room)}return json(res,200,view(room,p.id))}
return json(res,404,{error:'not found'})
}catch(e){return json(res,e?.status===413?413:400,{error:e?.status===413?'요청 데이터가 너무 큽니다.':'잘못된 요청입니다.'},req)}}
function allPlayersGone(room,now){
  if(room.players.size===0)return true;
  for(const p of room.players.values()){
    if(p.left)continue;
    if(!p.lastSeen||now-p.lastSeen<DISCONNECT_GRACE_MS)return false;
  }
  return true;
}
setInterval(()=>{
  const now=Date.now();
  for(const [k,x] of rate) if(now-x.t>120000) rate.delete(k);
  for(const [t,s] of sessions) if(s.exp<now) sessions.delete(t);
  for(const [c,r] of rooms){
    if(allPlayersGone(r,now)){
      if(!r.emptySince)r.emptySince=now;
      if(now-r.emptySince>=ROOM_TTL_MS){
        for(const [t,s] of sessions) if(s.room===r.code) sessions.delete(t);
        rooms.delete(c);
        continue;
      }
    }else r.emptySince=0
    if(r.dayBattle?.active){tickDayBattle(r);finishDayBattle(r);}
    if(r.started&&!r.finished&&!r.dayBattle?.active){markAutoReadyIfBroke(r,now);markDisconnectedReady(r,now);if([...r.players.values()].every(x=>x.ready)) advance(r);else if(now>=r.deadline) advance(r)}
  }
},1000);
http.createServer(handler).listen(PORT,()=>console.log(`TIME&MONEY v6 server on ${PORT}`));
