const http=require('http');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const PORT=process.env.PORT||3000,TURN_MS=3*60*1000,DAYTRADE_MS=30*1000,MAX_PLAYERS=8,rooms=new Map(),sessions=new Map(),rate=new Map();
const ASSETS=JSON.parse(fs.readFileSync(path.join(__dirname,'session2_assets.json'),'utf8'));
const ASSET=new Map(ASSETS.map(a=>[a.id,a]));
function json(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer'});res.end(body)}
function ip(req){return (req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim()}
function limited(req){const k=ip(req),now=Date.now(),x=rate.get(k)||{t:now,n:0};if(now-x.t>60000){x.t=now;x.n=0}x.n++;rate.set(k,x);return x.n>240}
function token(){return crypto.randomBytes(32).toString('hex')}
function roomCode(){let c;do c=String(crypto.randomInt(0,1000000)).padStart(6,'0');while(rooms.has(c));return c}
function safeName(n){return String(n||'Player').trim().slice(0,20)||'Player'}
function hash32(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function unitPrice(a,y,m){if(y<a.year)return 0;let p=Number(a.base)||1;for(let yy=a.year;yy<=y;yy++){for(let mm=1;mm<=12;mm++){if(yy===a.year&&mm===1)continue;if(yy===y&&mm>m)break;let n=(hash32(`${a.id}|${yy}|${mm}`)/4294967296)-.5;let r=n*2*Number(a.vol||.02);if(yy===1997)r-=.035*(a.kind==='bonds'?.2:1);if(yy===1998)r+=.018;if(yy===2000&&/tech|over|fund/.test(a.kind))r-=.04;if(yy===2008&&a.kind!=='bonds'&&a.kind!=='gold')r-=.055;if(yy===2020&&a.kind==='coin')r+=.025;p=Math.max(a.kind==='coin'?.000001:.01,p*(1+r))}}return a.kind==='coin'?Number(p.toFixed(6)):Math.round(p)}
function market(room){if(!room.marketPrices)room.marketPrices={};for(const a of ASSETS)if(a.year<=room.year)room.marketPrices[a.id]=unitPrice(a,room.year,room.month);return room.marketPrices}
function positionValue(p,room){let n=0,prices=room.marketPrices||{};for(const [id,q] of Object.entries(p.positions||{})){const a=ASSET.get(id),price=prices[id];if(a&&price)n+=Number(q)*price*(Number(a.multiplier)||1)}return Math.round(n)}
function netWorth(p,room){let v=(Number(p.cash)||0)+positionValue(p,room)-Number(p.loan||0)-Number(p.loanShark||0);const d=room.dayTrade;if(d&&d.active){const q=Number(d.positions?.[p.id]?.qty||0),cost=Number(d.positions?.[p.id]?.entryCost||0);v+=q*dayTradePrice(room)-cost}return Math.round(v)}
function dayTradePrice(room){const d=room.dayTrade;if(!d)return 0;if(Date.now()>=d.endAt)return d.lastPrice;let price=d.startPrice;const tick=Math.max(0,Math.floor((Date.now()-d.startAt)/1000));for(let i=1;i<=tick;i++){const n=(hash32(`${d.seed}|${i}`)/4294967296)-.5;price=Math.max(.01,price*(1+n*0.018))}return Number(price.toFixed(6))}
function settleDayTrade(room){const d=room.dayTrade;if(!d||d.settled)return;const price=dayTradePrice(room);for(const [pid,pos] of Object.entries(d.positions||{})){const p=room.players.get(pid);if(!p)continue;const qty=Number(pos.qty)||0;if(qty>0)p.cash+=qty*price;pos.qty=0;pos.settlePrice=price;pos.settled=true}d.lastPrice=price;d.settled=true;d.active=false}
function maybeStartDayTrade(room){if(room.dayTrade&&room.dayTrade.active)return;const should=crypto.randomInt(0,100)<40;if(!should){room.dayTrade=null;return}const available=ASSETS.filter(a=>a.year<=room.year&&a.kind!=='real'&&a.kind!=='bonds'&&a.kind!=='gold');if(!available.length){room.dayTrade=null;return}const a=available[crypto.randomInt(0,available.length)],start=Number(room.marketPrices[a.id]||unitPrice(a,room.year,room.month)||100);room.dayTrade={active:true,settled:false,assetId:a.id,assetName:a.name,startAt:Date.now(),endAt:Date.now()+DAYTRADE_MS,startPrice:start,lastPrice:start,seed:crypto.randomBytes(8).toString('hex'),positions:{}}}
function dayTradeView(room,p){const d=room.dayTrade;if(!d)return {active:false};if(d.active&&Date.now()>=d.endAt)settleDayTrade(room);const current=d.lastPrice=d.active?dayTradePrice(room):Number(d?.lastPrice||0);const mine=d?.positions?.[p?.id]||{qty:0,entryCost:0,realized:0};return {active:!!d?.active,settled:!!d?.settled,assetId:d?.assetId||null,assetName:d?.assetName||null,startPrice:Number(d?.startPrice||0),currentPrice:Number(current||0),startAt:d?.startAt||0,endAt:d?.endAt||0,serverNow:Date.now(),myQty:Number(mine.qty||0),myEntryCost:Number(mine.entryCost||0),myRealized:Number(mine.realized||0),myUnrealized:Number(mine.qty||0)*Number(current||0)-Number(mine.entryCost||0)}}
function publicView(room,me){const players=[...room.players.values()];players.sort((a,b)=>netWorth(b,room)-netWorth(a,room));return {id:me?.id||'',name:me?.name||'',roomCode:room.code,hostId:room.hostId,started:room.started,finished:room.finished,startAt:room.startAt||0,countdownActive:!!(room.startAt&&!room.started),year:room.year,month:room.month,turn:room.turn,deadline:room.deadline,playerCount:players.length,readyCount:players.filter(x=>x.ready).length,meReady:!!me?.ready,canStart:players.length>=2&&room.hostId===me?.id&&!room.started&&!room.finished,players:players.map((x,i)=>({id:x.id,name:x.name,ready:!!x.ready,rank:i+1,netWorth:netWorth(x,room)})),leaderboard:players.map((x,i)=>({rank:i+1,name:x.name,netWorth:netWorth(x,room)})),market:market(room),dayTrade:dayTradeView(room,me)}}
function privateState(room,p){return {cash:p.cash,positions:p.positions||{},avg:p.avg||{},loan:p.loan||0,loanShark:p.loanShark||0,netWorth:netWorth(p,room)}}
function view(room,p){const v=publicView(room,p);v.me=privateState(room,p);return v}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>200000)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function auth(room,t){const x=sessions.get(t);if(!x||x.room!==room.code||x.exp<Date.now()){if(x&&x.exp<Date.now())sessions.delete(t);return null}return room.players.get(x.id)||null}
function startRoom(room){if(room.started||room.finished||room.players.size<2)return false;room.startAt=0;room.started=true;room.year=1990;room.month=1;room.turn=0;room.deadline=Date.now()+TURN_MS;market(room);for(const p of room.players.values()){p.ready=false;p.cash=100000000;p.positions={};p.avg={};p.loan=0;p.loanShark=0}maybeStartDayTrade(room);return true}
function advanceRound(room){if(room.finished)return {advanced:false,finished:true};if(room.players.size<2){room.finished=true;return {advanced:false,finished:true}};settleDayTrade(room);room.month++;if(room.month>12){room.month=1;room.year++}if(room.year>2026){room.finished=true;room.deadline=0;for(const p of room.players.values())p.ready=false;return {advanced:false,finished:true}}room.turn++;for(const p of room.players.values()){p.ready=false;if(p.loan)p.loan=Math.round(p.loan*1.01);if(p.loanShark)p.loanShark=Math.round(p.loanShark*1.05)}room.deadline=Date.now()+TURN_MS;market(room);maybeStartDayTrade(room);return {advanced:true,finished:false,readyCount:0,playerCount:room.players.size}}
function create(name){const code=roomCode(),id=crypto.randomUUID(),t=token();const room={code,hostId:id,year:1990,month:1,turn:0,turnIndex:0,turnOrder:[],deadline:0,startAt:0,started:false,finished:false,players:new Map(),marketPrices:{},dayTrade:null};rooms.set(code,room);const p={id,name:safeName(name),cash:100000000,positions:{},avg:{},loan:0,loanShark:0,ready:false};room.players.set(id,p);sessions.set(t,{room:code,id,exp:Date.now()+86400000});return {room,player:p,token:t}}
async function handler(req,res){if(limited(req))return json(res,429,{error:'rate limit'});const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(__dirname,'index.html')).pipe(res)}try{
if(req.method==='POST'&&u.pathname==='/api/rooms'){const b=await body(req),r=create(b.name);return json(res,200,{...view(r.room,r.player),sessionToken:r.token,playerId:r.player.id})}
if(req.method==='POST'&&u.pathname==='/api/rooms/join'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});if(room.finished||room.started)return json(res,409,{error:'이미 시작되었거나 종료된 방입니다.'});if(room.players.size>=MAX_PLAYERS)return json(res,409,{error:'방이 가득 찼습니다. 최대 8명입니다.'});const id=crypto.randomUUID(),t=token(),p={id,name:safeName(b.name),cash:100000000,positions:{},avg:{},loan:0,loanShark:0,ready:false};room.players.set(id,p);sessions.set(t,{room:room.code,id,exp:Date.now()+86400000});return json(res,200,{...view(room,p),sessionToken:t,playerId:id})}
if(req.method==='POST'&&u.pathname==='/api/rooms/ready'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(room.finished)return json(res,409,{error:'이미 종료된 대전입니다.'});if(!room.started)return json(res,200,view(room,p));if(p.ready)return json(res,200,{...view(room,p),advanced:false,waiting:true,readyCount:[...room.players.values()].filter(x=>x.ready).length,playerCount:room.players.size});p.ready=true;const readyCount=[...room.players.values()].filter(x=>x.ready).length;if(readyCount===room.players.size){const result=advanceRound(room);return json(res,200,{...view(room,p),...result})}return json(res,200,{...view(room,p),advanced:false,waiting:true,readyCount,playerCount:room.players.size})}
if(req.method==='POST'&&u.pathname==='/api/rooms/start'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(room.hostId!==p.id)return json(res,403,{error:'방장만 대전을 시작할 수 있습니다.'});if(room.players.size<2)return json(res,409,{error:'최소 2명이 필요합니다.'});if(room.started)return json(res,409,{error:'이미 시작된 대전입니다.'});room.startAt=Date.now()+5000;return json(res,200,view(room,p))}
if(req.method==='POST'&&u.pathname==='/api/rooms/trade'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'진행 중인 대전이 아닙니다.'});const a=ASSET.get(String(b.assetId||''));const side=b.side,qty=Number(b.qty);if(!a||!['buy','sell'].includes(side)||!Number.isInteger(qty)||qty<1)return json(res,400,{error:'잘못된 거래입니다.'});if(a.year>room.year)return json(res,409,{error:'아직 거래할 수 없는 자산입니다.'});const price=Number(room.marketPrices[a.id]||0),unit=price*(Number(a.multiplier)||1),value=qty*unit;if(!price||!Number.isFinite(value))return json(res,409,{error:'시장 가격을 확인할 수 없습니다.'});const owned=Number(p.positions[a.id]||0);if(side==='buy'){if(p.cash<value)return json(res,409,{error:'현금이 부족합니다.'});const old=owned,oldAvg=Number(p.avg[a.id]||0);p.cash-=value;p.positions[a.id]=old+qty;p.avg[a.id]=old?((oldAvg*old)+value)/(old+qty):value}else{if(owned<qty)return json(res,409,{error:'보유 수량이 부족합니다.'});p.cash+=value;p.positions[a.id]=owned-qty;if(!p.positions[a.id])delete p.positions[a.id],delete p.avg[a.id]}return json(res,200,{...view(room,p),trade:{assetId:a.id,side,qty,value,price}})}
if(req.method==='POST'&&u.pathname==='/api/rooms/loan'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'진행 중인 대전이 아닙니다.'});const kind=b.kind==='shark'?'shark':'bank',amount=Number(b.amount);if(!Number.isInteger(amount)||amount<1)return json(res,400,{error:'대출 금액이 잘못되었습니다.'});const nw=Math.max(0,netWorth(p,room)),max=kind==='bank'?Math.floor(nw*1.5):Math.floor(nw*4),used=kind==='bank'?p.loan:p.loanShark,roomLimit=Math.max(0,max-used),v=Math.min(amount,roomLimit);if(v<1)return json(res,409,{error:'대출 한도가 없습니다.'});if(kind==='bank')p.loan+=v;else p.loanShark+=v;p.cash+=v;return json(res,200,view(room,p))}
if(req.method==='POST'&&u.pathname==='/api/rooms/progress'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started)return json(res,409,{error:'아직 시작되지 않았습니다.'});if(room.finished)return json(res,200,view(room,p));if(p.ready)return json(res,200,{...view(room,p),advanced:false,waiting:true,readyCount:[...room.players.values()].filter(x=>x.ready).length,playerCount:room.players.size});p.ready=true;const readyCount=[...room.players.values()].filter(x=>x.ready).length;if(readyCount<room.players.size)return json(res,200,{...view(room,p),advanced:false,waiting:true,readyCount,playerCount:room.players.size});const result=advanceRound(room);return json(res,200,{...view(room,p),...result})}
if(req.method==='POST'&&u.pathname==='/api/rooms/daytrade'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});if(!room.started||room.finished)return json(res,409,{error:'진행 중인 대전이 아닙니다.'});const d=room.dayTrade;if(!d||!d.active)return json(res,409,{error:'현재 랜덤 단타 이벤트가 없습니다.'});if(Date.now()>=d.endAt){settleDayTrade(room);return json(res,200,{...view(room,p),dayTrade:dayTradeView(room,p),settled:true})}const side=b.side,qty=Number(b.qty);if(!['buy','sell'].includes(side)||!Number.isInteger(qty)||qty<1)return json(res,400,{error:'잘못된 단타 거래입니다.'});const price=dayTradePrice(room),pos=d.positions[p.id]||(d.positions[p.id]={qty:0,entryCost:0,realized:0});if(side==='buy'){const value=qty*price;if(p.cash<value)return json(res,409,{error:'현금이 부족합니다.'});p.cash-=value;pos.qty+=qty;pos.entryCost+=value}else{if(pos.qty<qty)return json(res,409,{error:'단타 보유수량이 부족합니다.'});const value=qty*price;p.cash+=value;pos.qty-=qty;const avg=pos.entryCost/(pos.qty+qty);pos.entryCost=Math.max(0,pos.entryCost-avg*qty);pos.realized+=value-avg*qty}d.lastPrice=price;return json(res,200,{...view(room,p),dayTrade:dayTradeView(room,p),dayTradeTrade:{side,qty,price}})}
if(req.method==='POST'&&u.pathname==='/api/rooms/leave'){const b=await body(req),room=rooms.get(String(b.roomCode||''));if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,b.sessionToken);if(!p)return json(res,401,{error:'인증 실패'});room.players.delete(p.id);sessions.delete(b.sessionToken);room.turnOrder=room.turnOrder.filter(id=>id!==p.id);if(room.hostId===p.id)room.hostId=room.players.keys().next().value||null;if(room.turnIndex>=room.turnOrder.length)room.turnIndex=0;if(room.players.size===0)rooms.delete(room.code);return json(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname.startsWith('/api/rooms/')){const code=u.pathname.split('/').pop(),room=rooms.get(code),t=u.searchParams.get('sessionToken');if(!room)return json(res,404,{error:'방을 찾을 수 없습니다.'});const p=auth(room,t);if(!p)return json(res,401,{error:'인증 실패'});if(room.startAt&&Date.now()>=room.startAt&&!room.started)startRoom(room);if(room.started&&!room.finished&&room.dayTrade?.active&&Date.now()>=room.dayTrade.endAt){settleDayTrade(room)}return json(res,200,view(room,p))}
return json(res,404,{error:'not found'})}catch(e){console.error(e);return json(res,400,{error:'bad request'})}}
setInterval(()=>{const now=Date.now();for(const [t,s] of sessions)if(s.exp<now)sessions.delete(t);for(const [c,r] of rooms){if(r.players.size===0){rooms.delete(c);continue}if(r.startAt&&now>=r.startAt&&!r.started)startRoom(r);if(r.started&&!r.finished&&r.dayTrade?.active&&now>=r.dayTrade.endAt)settleDayTrade(r)}},1000);
http.createServer(handler).listen(PORT,()=>console.log(`TIME&MONEY Session 2 server on ${PORT}`));
